// SPLENDID'S ACADEMY CENTRAL QUESTION BANK
// Database Version: 4.0 (COMPLETE MERGE: ANA + PHS)
// Contains: ANA 211, ANA 213, PHS 211, PHS 212, PHS 213, PHS 214

const QUESTION_VAULT = {
    
    // =========================================
    // 💀 DEPARTMENT OF ANATOMY
    // =========================================

    "ANA 211": {
        beginner: [
            { q: "The bone of the arm is called the:", options: ["Radius", "Ulna", "Humerus", "Scapula"], a: 2 },
            { q: "Which bone is located on the thumb side of the forearm?", options: ["Ulna", "Radius", "Humerus", "Clavicle"], a: 1 },
            { q: "The collarbone is anatomically known as the:", options: ["Sternum", "Scapula", "Clavicle", "Vertebra"], a: 2 },
            { q: "The shoulder blade is the:", options: ["Clavicle", "Scapula", "Sternum", "Rib"], a: 1 },
            { q: "How many carpal bones are in the wrist?", options: ["5", "7", "8", "10"], a: 2 },
            { q: "The longest bone in the body is the:", options: ["Tibia", "Fibula", "Femur", "Humerus"], a: 2 },
            { q: "The kneecap is called the:", options: ["Fabella", "Patella", "Meniscus", "Tibia"], a: 1 },
            { q: "Which bone is the lateral bone of the leg?", options: ["Tibia", "Fibula", "Femur", "Talus"], a: 1 },
            { q: "The heel bone is the:", options: ["Talus", "Calcaneus", "Navicular", "Cuboid"], a: 1 },
            { q: "The shin bone is the:", options: ["Fibula", "Femur", "Tibia", "Patella"], a: 2 },
            { q: "Which muscle flexes the elbow?", options: ["Triceps brachii", "Biceps brachii", "Deltoid", "Trapezius"], a: 1 },
            { q: "The muscle forming the rounded contour of the shoulder is:", options: ["Pectoralis major", "Deltoid", "Latissimus dorsi", "Trapezius"], a: 1 },
            { q: "The primary muscle of the calf is:", options: ["Tibialis anterior", "Gastrocnemius", "Peroneus longus", "Extensor digitorum"], a: 1 },
            { q: "Which muscle extends the knee?", options: ["Quadriceps femoris", "Hamstrings", "Sartorius", "Gracilis"], a: 0 },
            { q: "The gluteus maximus is located in the:", options: ["Thigh", "Buttock", "Leg", "Back"], a: 1 },
            { q: "Which muscle group is on the posterior thigh?", options: ["Quadriceps", "Hamstrings", "Adductors", "Abductors"], a: 1 },
            { q: "The 'Boxer's muscle' is the:", options: ["Serratus anterior", "Pectoralis minor", "Deltoid", "Trapezius"], a: 0 },
            { q: "Which muscle extends the elbow?", options: ["Biceps", "Brachialis", "Triceps", "Coracobrachialis"], a: 2 },
            { q: "The 'Tailor's muscle' is the:", options: ["Sartorius", "Gracilis", "Rectus femoris", "Vastus medialis"], a: 0 },
            { q: "Adductor muscles are found in the:", options: ["Lateral thigh", "Medial thigh", "Anterior thigh", "Posterior thigh"], a: 1 },
            { q: "The hip joint is a:", options: ["Hinge joint", "Ball and socket joint", "Pivot joint", "Saddle joint"], a: 1 },
            { q: "The elbow joint is a:", options: ["Ball and socket joint", "Hinge joint", "Gliding joint", "Pivot joint"], a: 1 },
            { q: "The 'Big Toe' is called the:", options: ["Pollex", "Hallux", "Index", "Minimus"], a: 1 },
            { q: "The thumb is called the:", options: ["Pollex", "Hallux", "Index", "Medius"], a: 0 },
            { q: "Abduction means moving a limb:", options: ["Toward the midline", "Away from the midline", "In a circle", "Forward"], a: 1 },
            { q: "Adduction means moving a limb:", options: ["Toward the midline", "Away from the midline", "Backward", "Upward"], a: 0 },
            { q: "The anatomical term for the armpit is:", options: ["Cubital fossa", "Axilla", "Inguinal region", "Popliteal fossa"], a: 1 },
            { q: "The depression behind the knee is the:", options: ["Cubital fossa", "Popliteal fossa", "Axilla", "Fovea"], a: 1 },
            { q: "Which artery is used for pulse at the wrist?", options: ["Brachial", "Radial", "Ulnar", "Axillary"], a: 1 },
            { q: "How many phalanges are in the thumb?", options: ["1", "2", "3", "4"], a: 1 }
        ],
        intermediate: [
            { q: "The brachial plexus originates from nerve roots:", options: ["C1-C4", "C5-T1", "T1-T5", "L1-L4"], a: 1 },
            { q: "Which nerve passes through the carpal tunnel?", options: ["Ulnar", "Radial", "Median", "Musculocutaneous"], a: 2 },
            { q: "The 'Funny Bone' sensation is the:", options: ["Radial nerve", "Ulnar nerve", "Median nerve", "Axillary nerve"], a: 1 },
            { q: "The femoral nerve supplies the:", options: ["Posterior thigh", "Medial thigh", "Anterior thigh", "Gluteal region"], a: 2 },
            { q: "Sciatic nerve divides into:", options: ["Femoral and Obturator", "Tibial and Common Peroneal", "Radial and Ulnar", "Gluteal nerves"], a: 1 },
            { q: "Which vein runs in the deltopectoral groove?", options: ["Basilic", "Cephalic", "Median cubital", "Brachial"], a: 1 },
            { q: "The Great Saphenous Vein drains into the:", options: ["Popliteal vein", "Femoral vein", "External iliac vein", "Internal iliac vein"], a: 1 },
            { q: "Which artery runs in the spiral groove?", options: ["Brachial", "Profunda brachii", "Radial", "Ulnar"], a: 1 },
            { q: "The superficial palmar arch is mainly formed by the:", options: ["Radial artery", "Ulnar artery", "Brachial artery", "Axillary artery"], a: 1 },
            { q: "Dorsalis pedis artery is a continuation of:", options: ["Posterior tibial", "Anterior tibial", "Peroneal", "Popliteal"], a: 1 },
            { q: "The musculocutaneous nerve innervates:", options: ["Extensors of arm", "Flexors of arm", "Flexors of forearm", "Hand muscles"], a: 1 },
            { q: "Which nerve innervates the deltoid?", options: ["Radial", "Axillary", "Suprascapular", "Musculocutaneous"], a: 1 },
            { q: "The obturator nerve supplies the:", options: ["Anterior thigh", "Medial thigh", "Posterior thigh", "Leg"], a: 1 },
            { q: "Sensation to the lateral foot is supplied by:", options: ["Saphenous nerve", "Sural nerve", "Deep peroneal nerve", "Femoral nerve"], a: 1 },
            { q: "Which nerve is endangered in mid-shaft humerus fracture?", options: ["Axillary", "Radial", "Ulnar", "Median"], a: 1 },
            { q: "Which muscle unlocks the knee?", options: ["Popliteus", "Plantaris", "Soleus", "Gastrocnemius"], a: 0 },
            { q: "The rotator cuff muscle that abducts the arm is:", options: ["Supraspinatus", "Infraspinatus", "Teres minor", "Subscapularis"], a: 0 },
            { q: "Which muscle is the chief flexor of the hip?", options: ["Rectus femoris", "Iliopsoas", "Sartorius", "Gluteus medius"], a: 1 },
            { q: "The Achilles tendon attaches to the:", options: ["Talus", "Calcaneus", "Navicular", "Tibia"], a: 1 },
            { q: "Which muscle forms the floor of the snuffbox?", options: ["Supinator", "Pronator teres", "Brachialis", "Anconeus"], a: 0 },
            { q: "The adductor magnus has a:", options: ["Hamstring and Adductor part", "Quadriceps part", "Gluteal part", "Flexor part"], a: 0 },
            { q: "Inversion of the foot is caused by:", options: ["Peroneus longus", "Tibialis anterior & posterior", "Gastrocnemius", "Soleus"], a: 1 },
            { q: "The coracoid process anchors the:", options: ["Pectoralis major", "Pectoralis minor", "Deltoid", "Latissimus dorsi"], a: 1 },
            { q: "Which muscle protracts the scapula?", options: ["Rhomboids", "Trapezius", "Serratus anterior", "Levator scapulae"], a: 2 },
            { q: "The triceps brachii has how many heads?", options: ["Two", "Three", "Four", "One"], a: 1 },
            { q: "Which muscle is absent in 14% of people?", options: ["Palmaris longus", "Flexor carpi radialis", "Pronator teres", "Supinator"], a: 0 },
            { q: "The hamstrings originate from the:", options: ["Iliac crest", "Ischial tuberosity", "Pubic symphysis", "Sacrum"], a: 1 },
            { q: "Which muscle laterally rotates the thigh?", options: ["Gluteus minimus", "Piriformis", "Tensor fascia lata", "Pectineus"], a: 1 },
            { q: "The thenar muscles act on the:", options: ["Thumb", "Little finger", "Index finger", "Wrist"], a: 0 },
            { q: "Lumbricals flex the:", options: ["DIP joints", "PIP joints", "MCP joints", "Wrist"], a: 2 },
            { q: "The glenoid labrum increases depth of the:", options: ["Hip joint", "Shoulder joint", "Knee joint", "Elbow joint"], a: 1 },
            { q: "Which ligament prevents hyperextension of the hip?", options: ["Iliofemoral", "Ischiofemoral", "Pubofemoral", "Round ligament"], a: 0 },
            { q: "The cruciate ligaments are found in the:", options: ["Elbow", "Knee", "Hip", "Ankle"], a: 1 },
            { q: "The deltoid ligament stabilizes the:", options: ["Lateral ankle", "Medial ankle", "Knee", "Shoulder"], a: 1 },
            { q: "Which meniscus is C-shaped?", options: ["Medial", "Lateral", "Both", "Neither"], a: 0 },
            { q: "The annular ligament stabilizes the:", options: ["Head of humerus", "Head of radius", "Head of femur", "Head of ulna"], a: 1 },
            { q: "Supination and pronation occur at:", options: ["Radio-ulnar joints", "Elbow hinge", "Wrist", "Shoulder"], a: 0 },
            { q: "The symphysis pubis is a:", options: ["Synovial joint", "Cartilaginous joint", "Fibrous joint", "Bony joint"], a: 1 },
            { q: "The spring ligament supports the:", options: ["Lateral longitudinal arch", "Medial longitudinal arch", "Transverse arch", "Ankle joint"], a: 1 },
            { q: "Bouchard's nodes occur at:", options: ["DIP joints", "PIP joints", "MCP joints", "Wrist"], a: 1 }
        ],
        advanced: [
            { q: "Erb-Duchenne palsy involves nerve roots:", options: ["C8-T1", "C5-C6", "C7", "T1-T2"], a: 1 },
            { q: "Klumpke's paralysis affects the:", options: ["Upper trunk", "Middle trunk", "Lower trunk", "Posterior cord"], a: 2 },
            { q: "Winged scapula indicates damage to:", options: ["Axillary nerve", "Long thoracic nerve", "Dorsal scapular nerve", "Suprascapular nerve"], a: 1 },
            { q: "Wrist drop is a sign of:", options: ["Median nerve injury", "Ulnar nerve injury", "Radial nerve injury", "Axillary nerve injury"], a: 2 },
            { q: "Claw hand is typical of:", options: ["Radial nerve palsy", "High median nerve palsy", "Ulnar nerve palsy", "Musculocutaneous nerve palsy"], a: 2 },
            { q: "Ape hand deformity involves atrophy of:", options: ["Hypothenar eminence", "Thenar eminence", "Interossei", "Lumbricals"], a: 1 },
            { q: "Saturday night palsy affects the:", options: ["Radial nerve in spiral groove", "Ulnar nerve at elbow", "Median nerve at wrist", "Axillary nerve"], a: 0 },
            { q: "Fracture of the medial epicondyle endangers:", options: ["Radial nerve", "Median nerve", "Ulnar nerve", "Musculocutaneous nerve"], a: 2 },
            { q: "Colles' fracture involves the:", options: ["Proximal radius", "Distal radius", "Scaphoid", "Ulna"], a: 1 },
            { q: "Smith's fracture is also called:", options: ["Reverse Colles'", "Boxer's fracture", "Monteggia", "Galeazzi"], a: 0 },
            { q: "Dupuytren's contracture affects the:", options: ["Flexor tendons", "Palmar aponeurosis", "Extensor hood", "Thenar fascia"], a: 1 },
            { q: "Tennis elbow is:", options: ["Medial epicondylitis", "Lateral epicondylitis", "Olecranon bursitis", "Radial tunnel syndrome"], a: 1 },
            { q: "Golfer's elbow is:", options: ["Medial epicondylitis", "Lateral epicondylitis", "Cubital tunnel syndrome", "Pronator syndrome"], a: 0 },
            { q: "Scaphoid fracture tenderness is found in:", options: ["Carpal tunnel", "Anatomical snuffbox", "Guyon's canal", "Palm"], a: 1 },
            { q: "Volkmann's contracture results from:", options: ["Nerve injury", "Ischemia/Compartment syndrome", "Tendon rupture", "Bone infection"], a: 1 },
            { q: "Trendelenburg sign indicates weakness of:", options: ["Gluteus maximus", "Gluteus medius/minimus", "Quadriceps", "Adductors"], a: 1 },
            { q: "Foot drop is caused by damage to:", options: ["Tibial nerve", "Common peroneal nerve", "Femoral nerve", "Obturator nerve"], a: 1 },
            { q: "Unhappy triad includes ACL, Medial Meniscus and:", options: ["LCL", "MCL", "PCL", "Patella"], a: 1 },
            { q: "Housemaid's knee is:", options: ["Prepatellar bursitis", "Suprapatellar bursitis", "Infrapatellar bursitis", "Popliteal cyst"], a: 0 },
            { q: "Baker's cyst is found in the:", options: ["Ankle", "Popliteal fossa", "Cubital fossa", "Axilla"], a: 1 },
            { q: "Pott's fracture occurs at the:", options: ["Hip", "Knee", "Ankle", "Foot"], a: 2 },
            { q: "Femoral hernia is more common in:", options: ["Males", "Females", "Children", "Athletes"], a: 1 },
            { q: "Meralgia paresthetica involves the:", options: ["Femoral nerve", "Lateral cutaneous nerve of thigh", "Obturator nerve", "Sciatic nerve"], a: 1 },
            { q: "Positive anterior drawer sign indicates:", options: ["PCL tear", "ACL tear", "Meniscus tear", "MCL tear"], a: 1 },
            { q: "Varicose veins commonly affect the:", options: ["Deep veins", "Great saphenous vein", "Popliteal vein", "Femoral vein"], a: 1 },
            { q: "Safe site for intragluteal injection is:", options: ["Upper medial", "Lower medial", "Upper lateral", "Lower lateral"], a: 2 },
            { q: "Piriformis syndrome compresses the:", options: ["Femoral nerve", "Sciatic nerve", "Obturator nerve", "Gluteal nerve"], a: 1 },
            { q: "Hallux valgus is commonly known as:", options: ["Flat foot", "Bunion", "Club foot", "Hammer toe"], a: 1 },
            { q: "Pes planus refers to:", options: ["High arch", "Flat foot", "Club foot", "Claw foot"], a: 1 },
            { q: "Intermittent claudication suggests:", options: ["Venous insufficiency", "Arterial insufficiency", "Nerve compression", "Muscle strain"], a: 1 },
            { q: "Contents of femoral triangle (Lateral to Medial):", options: ["VAN", "NAV", "AVN", "VNA"], a: 1 },
            { q: "Quadrangular space transmits:", options: ["Radial nerve", "Axillary nerve & post. circumflex artery", "Ulnar nerve", "Suprascapular nerve"], a: 1 },
            { q: "Triangular interval transmits:", options: ["Radial nerve & profunda brachii", "Axillary nerve", "Circumflex scapular artery", "Median nerve"], a: 0 },
            { q: "Adductor canal contains:", options: ["Femoral artery, vein, saphenous nerve", "Sciatic nerve", "Obturator nerve", "Profunda artery"], a: 0 },
            { q: "Structures passing deep to flexor retinaculum: Tom, Dick, And Very Nervous Harry. 'Nervous' is:", options: ["Deep peroneal", "Tibial nerve", "Sural nerve", "Saphenous nerve"], a: 1 },
            { q: "Floor of femoral triangle:", options: ["Iliopsoas, Pectineus", "Adductor magnus", "Sartorius", "Rectus femoris"], a: 0 },
            { q: "Roof of cubital fossa contains:", options: ["Bicipital aponeurosis", "Brachialis", "Supinator", "Pronator teres"], a: 0 },
            { q: "Guyon's canal contains:", options: ["Median nerve", "Ulnar nerve & artery", "Radial nerve", "Palmaris longus"], a: 1 },
            { q: "Structure posterior to medial malleolus:", options: ["Great saphenous vein", "Tibialis anterior", "Tibialis posterior", "Peroneus longus"], a: 2 },
            { q: "Lymph from lateral foot drains to:", options: ["Superficial inguinal", "Popliteal nodes", "Deep inguinal", "Iliac nodes"], a: 1 },
            { q: "Locking of the knee involves:", options: ["Lateral rotation of femur", "Medial rotation of femur on tibia", "Flexion", "Abduction"], a: 1 },
            { q: "Unlocking of the knee is done by:", options: ["Popliteus", "Plantaris", "Soleus", "Biceps femoris"], a: 0 },
            { q: "Carrying angle is greater in:", options: ["Males", "Females", "Children", "Elderly"], a: 1 },
            { q: "Keystone of medial longitudinal arch:", options: ["Calcaneus", "Talus head", "Navicular", "Cuneiform"], a: 1 },
            { q: "Keystone of lateral longitudinal arch:", options: ["Cuboid", "Calcaneus", "Talus", "Metatarsals"], a: 0 },
            { q: "Primary support of the arches:", options: ["Shape of bones", "Ligaments", "Plantaris", "Spring ligament & Plantar aponeurosis"], a: 3 },
            { q: "Lumbricals originate from:", options: ["Bones", "Flexor digitorum profundus tendons", "Extensor tendons", "Retinaculum"], a: 1 },
            { q: "Cruciate anastomosis connects:", options: ["External & Internal Iliac", "Femoral & Popliteal", "Iliac & Femoral", "Obturator & Sciatic"], a: 0 },
            { q: "Sural nerve is formed by:", options: ["Tibial & Common Peroneal", "Femoral", "Obturator", "Saphenous"], a: 0 },
            { q: "Saphenous nerve is a branch of:", options: ["Sciatic", "Femoral", "Obturator", "Tibial"], a: 1 }
        ]
    },

    "ANA 213": {
        beginner: [
            { q: "The process of sperm formation is:", options: ["Oogenesis", "Spermatogenesis", "Mitosis", "Meiosis"], a: 1 },
            { q: "The female gamete is the:", options: ["Sperm", "Oocyte", "Zygote", "Blastocyst"], a: 1 },
            { q: "Where are sperm produced?", options: ["Epididymis", "Seminiferous tubules", "Vas deferens", "Prostate"], a: 1 },
            { q: "Where does fertilization usually occur?", options: ["Uterus", "Ovary", "Ampulla of Uterine Tube", "Cervix"], a: 2 },
            { q: "A fertilized egg is called a:", options: ["Gamete", "Zygote", "Fetus", "Embryo"], a: 1 },
            { q: "The release of an egg from the ovary is:", options: ["Menstruation", "Ovulation", "Implantation", "Fertilization"], a: 1 },
            { q: "How many chromosomes does a normal zygote have?", options: ["23", "46", "92", "21"], a: 1 },
            { q: "The tail of the sperm is for:", options: ["Genetic storage", "Motility", "Penetration", "Energy"], a: 1 },
            { q: "The acrosome contains:", options: ["DNA", "Enzymes", "Mitochondria", "Ribosomes"], a: 1 },
            { q: "Ovulation typically occurs on day:", options: ["1", "14", "28", "7"], a: 1 },
            { q: "The solid ball of cells formed after cleavage is:", options: ["Blastocyst", "Morula", "Gastrula", "Neurula"], a: 1 },
            { q: "Implantation occurs in the:", options: ["Ovary", "Fallopian tube", "Endometrium of Uterus", "Cervix"], a: 2 },
            { q: "The outer layer of the blastocyst is the:", options: ["Embryoblast", "Trophoblast", "Hypoblast", "Epiblast"], a: 1 },
            { q: "The inner cell mass becomes the:", options: ["Placenta", "Embryo proper", "Amniotic sac", "Chorion"], a: 1 },
            { q: "HCG is produced by:", options: ["Ovary", "Syncytiotrophoblast", "Hypothalamus", "Pituitary"], a: 1 },
            { q: "The bilaminar disc consists of:", options: ["Ectoderm/Endoderm", "Epiblast/Hypoblast", "Mesoderm/Ectoderm", "Trophoblast/Embryoblast"], a: 1 },
            { q: "Normal implantation occurs on day:", options: ["1-2", "3-4", "6-7", "14-15"], a: 2 },
            { q: "Ectopic pregnancy most commonly occurs in:", options: ["Ovary", "Abdomen", "Uterine tube", "Cervix"], a: 2 },
            { q: "The cavity within the blastocyst is the:", options: ["Yolk sac", "Blastocoel", "Amnion", "Chorion"], a: 1 },
            { q: "The zona pellucida disappears before:", options: ["Fertilization", "Cleavage", "Implantation", "Ovulation"], a: 2 },
            { q: "Gastrulation forms how many germ layers?", options: ["1", "2", "3", "4"], a: 2 },
            { q: "The three germ layers are:", options: ["Epi, Hypo, Meso", "Ecto, Meso, Endo", "Tropho, Embryo, Blasto", "Outer, Middle, Inner"], a: 1 },
            { q: "The period from week 9 to birth is:", options: ["Embryonic", "Fetal", "Germinal", "Neonatal"], a: 1 },
            { q: "The organ of exchange between mother and fetus is:", options: ["Amnion", "Yolk sac", "Placenta", "Allantois"], a: 2 },
            { q: "The fluid surrounding the fetus is:", options: ["Plasma", "Amniotic fluid", "Chorionic fluid", "Yolk"], a: 1 },
            { q: "Teratology is the study of:", options: ["Cells", "Tissues", "Birth defects", "Tumors"], a: 2 },
            { q: "Which trimester is most critical for organogenesis?", options: ["First", "Second", "Third", "Fourth"], a: 0 },
            { q: "The umbilical cord normally contains:", options: ["2 veins, 1 artery", "2 arteries, 1 vein", "1 artery, 1 vein", "2 arteries, 2 veins"], a: 1 },
            { q: "Quickening refers to:", options: ["Rapid growth", "Fetal movements felt by mother", "Labor pains", "Head dropping"], a: 1 },
            { q: "Full term pregnancy is:", options: ["28 weeks", "32 weeks", "38-40 weeks", "45 weeks"], a: 2 }
        ],
        intermediate: [
            { q: "The nervous system is derived from:", options: ["Endoderm", "Mesoderm", "Ectoderm", "Neural crest only"], a: 2 },
            { q: "Muscles and bones are derived from:", options: ["Ectoderm", "Mesoderm", "Endoderm", "Hypoblast"], a: 1 },
            { q: "The gut lining is derived from:", options: ["Ectoderm", "Mesoderm", "Endoderm", "Epiblast"], a: 2 },
            { q: "The heart begins to beat on day:", options: ["14", "22", "35", "50"], a: 1 },
            { q: "The kidneys develop from:", options: ["Paraxial mesoderm", "Intermediate mesoderm", "Lateral plate mesoderm", "Endoderm"], a: 1 },
            { q: "Somites give rise to:", options: ["Skin, Muscle, Bone (Vertebrae)", "Brain, Eyes, Ears", "Liver, Pancreas, Gut", "Heart, Blood, Vessels"], a: 0 },
            { q: "The notochord induces formation of:", options: ["Gut tube", "Neural tube", "Heart tube", "Limb bud"], a: 1 },
            { q: "Neural crest cells form:", options: ["CNS", "PNS ganglia & Melanocytes", "Epidermis", "Muscle"], a: 1 },
            { q: "The liver develops from the:", options: ["Foregut", "Midgut", "Hindgut", "Proctodeum"], a: 0 },
            { q: "The lungs develop as a diverticulum of the:", options: ["Foregut", "Midgut", "Hindgut", "Neural tube"], a: 0 },
            { q: "Pharyngeal arches are visible in week:", options: ["2", "4", "8", "12"], a: 1 },
            { q: "The 1st pharyngeal arch forms the:", options: ["Mandible & Malleus/Incus", "Hyoid", "Thyroid", "Cricoid"], a: 0 },
            { q: "The placenta has two parts: Fetal (Chorion) and Maternal (________):", options: ["Amnion", "Decidua basalis", "Decidua capsularis", "Yolk sac"], a: 1 },
            { q: "Which vessel carries oxygenated blood to the fetus?", options: ["Umbilical artery", "Umbilical vein", "Aorta", "IVC"], a: 1 },
            { q: "The ductus arteriosus connects:", options: ["Umbilical vein to IVC", "Pulmonary trunk to Aorta", "Right atrium to Left atrium", "Aorta to Pulmonary vein"], a: 1 },
            { q: "The allantois becomes the:", options: ["Urachus/Median umbilical ligament", "Round ligament", "Ligamentum venosum", "Falciform ligament"], a: 0 },
            { q: "The ductus venosus shunts blood through the:", options: ["Heart", "Liver", "Lungs", "Kidney"], a: 1 },
            { q: "Oligohydramnios means:", options: ["Too much amniotic fluid", "Too little amniotic fluid", "Infected fluid", "Bloody fluid"], a: 1 },
            { q: "Polyhydramnios is associated with:", options: ["Renal agenesis", "Esophageal atresia/Anencephaly", "Heart defects", "Limb defects"], a: 1 },
            { q: "Cotyledons are found on the:", options: ["Fetal surface of placenta", "Maternal surface of placenta", "Amnion", "Umbilical cord"], a: 1 },
            { q: "Wharton's Jelly is found in:", options: ["Placenta", "Umbilical cord", "Amniotic fluid", "Yolk sac"], a: 1 },
            { q: "Dizygotic twins are:", options: ["Identical", "Fraternal", "Conjoined", "Clones"], a: 1 },
            { q: "Monozygotic twins splitting at 2-cell stage have:", options: ["2 Chorions, 2 Amnions", "1 Chorion, 2 Amnions", "1 Chorion, 1 Amnion", "Fused bodies"], a: 0 },
            { q: "The decidua capsularis covers the:", options: ["Implanted blastocyst", "Uterine wall", "Cervix", "Placenta base"], a: 0 },
            { q: "Gas exchange in placenta occurs in:", options: ["Chorionic plate", "Intervillous spaces", "Umbilical vessels", "Decidua"], a: 1 },
            { q: "The metanephros becomes the:", options: ["Pronephros", "Permanent kidney", "Gonad", "Ureter"], a: 1 },
            { q: "Surfactant is produced by:", options: ["Type I pneumocytes", "Type II pneumocytes", "Macrophages", "Bronchioles"], a: 1 },
            { q: "Testes descent is guided bbyguideddescentTestesy:", options: ["Gubernaculum", "Processus vaginalis", "Vas deferens", "Ureter"], a: 0 },
            { q: "The uterus is formed by fusion of:", options: ["Mesonephric ducts", "Paramesonephric (Mullerian) ducts", "Metanephric ducts", "Urachus"], a: 1 },
            { q: "Which arch nerve is the Facial nerve?", options: ["1st", "2nd", "3rd", "4th"], a: 1 }
        ],
        advanced: [
            { q: "Failure of the neural tube to close cranially causes:", options: ["Spina bifida", "Anencephaly", "Hydrocephalus", "Meningocele"], a: 1 },
            { q: "Failure of caudal closure causes:", options: ["Anencephaly", "Spina bifida", "Holoprosencephaly", "Encephalocele"], a: 1 },
            { q: "Thalidomide causes:", options: ["Amelia/Phocomelia (Limb defects)", "Heart defects", "Deafness", "Cataracts"], a: 0 },
            { q: "Rubella virus triad includes:", options: ["Cataract, Deafness, Heart defect", "Limb, Kidney, Liver", "Brain, Spine, Skin", "Lung, Gut, Bone"], a: 0 },
            { q: "Tetralogy of Fallot includes:", options: ["ASD, VSD, PDA, PS", "VSD, PS, Overriding Aorta, RV Hypertrophy", "Transposition, VSD, Coarctation", "Truncus arteriosus"], a: 1 },
            { q: "Hirschsprung's disease is due to failure of:", options: ["Neural crest migration to gut", "Gut rotation", "Anal membrane rupture", "Mesentery formation"], a: 0 },
            { q: "Meckel's Diverticulum is a remnant of:", options: ["Allantois", "Vitelline duct (Yolk stalk)", "Urachus", "Notochord"], a: 1 },
            { q: "Patent Ductus Arteriosus (PDA) causes a:", options: ["Right-to-Left shunt", "Left-to-Right shunt", "No shunt", "Cyanosis immediately"], a: 1 },
            { q: "Gastroschisis involves:", options: ["Herniation through umbilicus covered by amnion", "Herniation lateral to umbilicus (no sac)", "Failure of gut rotation", "Anal atresia"], a: 1 },
            { q: "Omphalocele is:", options: ["Herniation into umbilical cord (covered)", "Open wall defect", "Bladder exstrophy", "Diaphragmatic hernia"], a: 0 },
            { q: "Renal agenesis (Potter's sequence) causes:", options: ["Polyhydramnios", "Oligohydramnios & lung hypoplasia", "Hydrocephalus", "Macrosomia"], a: 1 },
            { q: "Cleft lip results from failure of fusion between:", options: ["Maxillary & Medial Nasal processes", "Medial & Lateral Nasal", "Palatine shelves", "Mandibular processes"], a: 0 },
            { q: "DiGeorge Syndrome involves defects in arches:", options: ["1 & 2", "3 & 4", "4 & 6", "1 & 6"], a: 1 },
            { q: "Fetal Alcohol Syndrome features:", options: ["Microcephaly, facial anomalies, growth retardation", "Limb defects", "Spina bifida", "Deafness"], a: 0 },
            { q: "Cryptorchidism is:", options: ["Undescended testes", "Missing testes", "Fluid in scrotum", "Hernia"], a: 0 },
            { q: "The primitive streak establishes:", options: ["Body axes (Cranial-Caudal)", "Limb bud", "Heart beat", "Placenta"], a: 0 },
            { q: "Notochord acts as a signaling center using:", options: ["SHH (Sonic Hedgehog)", "Insulin", "Testosterone", "Hemoglobin"], a: 0 },
            { q: "Apoptosis is essential for:", options: ["Digit separation", "Neurulation", "Gastrulation", "Fertilization"], a: 0 },
            { q: "ZPA (Zone of Polarizing Activity) regulates:", options: ["Limb Anterior-Posterior axis", "Head size", "Eye color", "Gut length"], a: 0 },
            { q: "AER (Apical Ectodermal Ridge) is essential for:", options: ["Limb outgrowth (Proximodistal)", "Muscle formation", "Nerve entry", "Bone hardening"], a: 0 },
            { q: "Sry gene on Y chromosome triggers:", options: ["Ovary formation", "Testis differentiation", "Kidney formation", "Lung growth"], a: 1 },
            { q: "Hox genes regulate:", options: ["Metabolism", "Body patterning/Segmentation", "Cell division speed", "Energy"], a: 1 },
            { q: "Holoprosencephaly is linked to defects in:", options: ["SHH signaling", "FGF", "Wnt", "Notch"], a: 0 },
            { q: "Capacitation of sperm occurs in:", options: ["Epididymis", "Female reproductive tract", "Seminal vesicle", "Urethra"], a: 1 },
            { q: "Cortical reaction prevents:", options: ["Implantation", "Polyspermy", "Ovulation", "Menstruation"], a: 1 },
            { q: "Compaction occurs at which stage?", options: ["Zygote", "8-cell / Morula", "Blastocyst", "Gastrula"], a: 1 },
            { q: "The prochordal plate marks the site of the:", options: ["Mouth (Oropharyngeal membrane)", "Anus", "Heart", "Liver"], a: 0 },
            { q: "Cloacal membrane becomes:", options: ["Mouth", "Anus/Urogenital openings", "Umbilicus", "Nose"], a: 1 },
            { q: "Midgut rotation totals:", options: ["90 deg", "180 deg", "270 deg counterclockwise", "360 deg"], a: 2 },
            { q: "Physiological herniation of gut occurs during week:", options: ["4-5", "6-10", "12-14", "20"], a: 1 },
            { q: "Thyroid gland originates from:", options: ["Foramen cecum (Tongue)", "Pharyngeal pouch 1", "Neural crest", "Rathke's pouch"], a: 0 },
            { q: "Parathyroid glands (inferior) come from pouch:", options: ["1", "2", "3", "4"], a: 2 },
            { q: "Thymus comes from pouch:", options: ["1", "2", "3", "4"], a: 2 },
            { q: "Ear ossicles (Malleus/Incus) come from arch:", options: ["1", "2", "3", "4"], a: 0 },
            { q: "Stapes comes from arch:", options: ["1", "2", "3", "4"], a: 1 },
            { q: "Rathke's pouch forms the:", options: ["Anterior Pituitary", "Posterior Pituitary", "Pineal gland", "Thyroid"], a: 0 },
            { q: "Neural tube defects are prevented by:", options: ["Vitamin C", "Folic Acid", "Iron", "Calcium"], a: 1 },
            { q: "Hydrocephalus is due to blockage of:", options: ["CSF flow (Aqueduct)", "Blood flow", "Urine", "Lymph"], a: 0 },
            { q: "Arnold-Chiari malformation involves:", options: ["Cerebellum herniation", "Missing cerebrum", "Fused eyes", "Cleft face"], a: 0 },
            { q: "Coloboma is a defect of the:", options: ["Ear", "Eye (Iris)", "Nose", "Lip"], a: 1 },
            { q: "The septum primum and secundum form the:", options: ["Interatrial septum", "Interventricular septum", "Aortic valve", "Mitral valve"], a: 0 },
            { q: "Persistent Truncus Arteriosus results from failure of:", options: ["Neural crest ridges to spiral", "Endocardial cushions", "Valve formation", "Atrial septation"], a: 0 },
            { q: "Transposition of Great Vessels is due to:", options: ["Straight (non-spiral) septum", "Missing septum", "Fused valves", "Small heart"], a: 0 },
            { q: "Coarctation of Aorta is:", options: ["Narrowing of aorta", "Missing aorta", "Double aorta", "Right-sided aorta"], a: 0 },
            { q: "Probe patent foramen ovale is found in:", options: ["1% of people", "25% of population", "100% of people", "Only babies"], a: 1 },
            { q: "Ligamentum arteriosum is the remnant of:", options: ["Ductus venosus", "Ductus arteriosus", "Umbilical vein", "Foramen ovale"], a: 1 },
            { q: "Fossa ovalis is the remnant of:", options: ["Ductus arteriosus", "Foramen ovale", "VSD", "ASD"], a: 1 },
            { q: "Ectopia cordis is:", options: ["Heart outside body", "Heart on right side", "Small heart", "Missing heart"], a: 0 },
            { q: "Dextrocardia with situs inversus is associated with:", options: ["Kartagener syndrome (Ciliary dyskinesia)", "Down syndrome", "Turner syndrome", "Marfan syndrome"], a: 0 },
            { q: "Angiogenesis refers to:", options: ["Blood cell formation", "Vessel formation from existing vessels", "Heart beating", "Valve closure"], a: 1 }
        ]
    },

    // =========================================
    // 💀 DEPARTMENT OF PHYSIOLOGY
    // =========================================

    "PHS 211": {
        beginner: [
            // 1-10: General & Plasma
            { q: "The normal pH range of arterial blood is:", options: ["7.00-7.10", "7.35-7.45", "7.50-7.60", "6.80-7.00"], a: 1 },
            { q: "The liquid portion of blood without clotting factors is called:", options: ["Plasma", "Serum", "Lymph", "Water"], a: 1 },
            { q: "Which plasma protein maintains oncotic pressure?", options: ["Fibrinogen", "Albumin", "Globulin", "Prothrombin"], a: 1 },
            { q: "Red blood cells are also known as:", options: ["Leukocytes", "Thrombocytes", "Erythrocytes", "Phagocytes"], a: 2 },
            { q: "The average lifespan of an RBC is:", options: ["30 days", "60 days", "90 days", "120 days"], a: 3 },
            { q: "Hypoxia stimulates the kidneys to secrete:", options: ["Renin", "Erythropoietin", "Aldosterone", "Cortisol"], a: 1 },
            { q: "Hemoglobin transports primarily:", options: ["Nutrients", "Oxygen", "Hormones", "Waste"], a: 1 },
            { q: "Iron is essential for the formation of:", options: ["Fibrin", "Heme", "Globin", "Albumin"], a: 1 },
            { q: "The breakdown product of Heme that causes jaundice is:", options: ["Iron", "Bilirubin", "Urea", "Creatinine"], a: 1 },
            { q: "Polycythemia refers to:", options: ["Low WBC count", "High RBC count", "Low Platelet count", "High Plasma volume"], a: 1 },
            // 11-20: WBCs & Immunity
            { q: "Which WBC is most abundant in normal blood?", options: ["Lymphocyte", "Monocyte", "Neutrophil", "Basophil"], a: 2 },
            { q: "Which WBC releases histamine?", options: ["Neutrophil", "Basophil", "Eosinophil", "Monocyte"], a: 1 },
            { q: "Antibodies are produced by:", options: ["T-cells", "B-cells (Plasma cells)", "Macrophages", "NK cells"], a: 1 },
            { q: "Phagocytosis is a primary function of:", options: ["Neutrophils & Macrophages", "Basophils", "Lymphocytes", "Platelets"], a: 0 },
            { q: "Which immunoglobulin crosses the placenta?", options: ["IgM", "IgA", "IgG", "IgE"], a: 2 },
            { q: "Innate immunity is:", options: ["Specific", "Non-specific", "Acquired", "Slow"], a: 1 },
            { q: "T-lymphocytes mature in the:", options: ["Bone marrow", "Thyroid", "Thymus", "Spleen"], a: 2 },
            { q: "HIV attacks which specific cell type?", options: ["CD8 T-cells", "CD4 Helper T-cells", "B-cells", "Neutrophils"], a: 1 },
            { q: "The first line of defense includes:", options: ["Antibodies", "Skin and Mucous membranes", "T-cells", "Vaccines"], a: 1 },
            { q: "Leukopenia means:", options: ["High WBC count", "Low WBC count", "Cancer of blood", "Low RBC count"], a: 1 },
            // 21-30: Haemostasis & Blood Groups
            { q: "Platelets are formed from:", options: ["Monocytes", "Megakaryocytes", "Reticulocytes", "Stem cells"], a: 1 },
            { q: "The first step in haemostasis is:", options: ["Coagulation", "Platelet plug", "Vascular spasm", "Fibrinolysis"], a: 2 },
            { q: "Vitamin K is required for clotting factors:", options: ["I, II, V", "II, VII, IX, X", "VIII, IX, XI", "XII, XIII"], a: 1 },
            { q: "The universal donor blood group is:", options: ["A Positive", "AB Positive", "O Negative", "B Negative"], a: 2 },
            { q: "The universal recipient blood group is:", options: ["O Positive", "A Positive", "AB Positive", "B Positive"], a: 2 },
            { q: "Antigens are located on the:", options: ["Plasma", "RBC membrane", "WBC nucleus", "Platelet surface"], a: 1 },
            { q: "Rh factor refers to antigen:", options: ["A", "B", "D", "O"], a: 2 },
            { q: "Thrombin converts Fibrinogen into:", options: ["Plasmin", "Fibrin", "Prothrombin", "Clot"], a: 1 },
            { q: "Hemophilia is a defect in:", options: ["Platelets", "Clotting factors", "Vessel walls", "RBCs"], a: 1 },
            { q: "Fibrinolysis is the process of:", options: ["Clot formation", "Clot dissolution", "Vessel constriction", "Platelet aggregation"], a: 1 }
        ],
        intermediate: [
            // 1-15: Erythropoiesis & Metabolism
            { q: "Which stage of erythropoiesis ejects the nucleus?", options: ["Proerythroblast", "Normoblast", "Reticulocyte", "Stem cell"], a: 1 },
            { q: "Reticulocytes contain remnants of:", options: ["DNA", "RNA (Ribosomes)", "Mitochondria", "Nucleus"], a: 1 },
            { q: "Intrinsic factor is secreted by the stomach for absorption of:", options: ["Iron", "Vitamin B12", "Folic Acid", "Calcium"], a: 1 },
            { q: "Iron is stored in the liver as:", options: ["Transferrin", "Ferritin", "Haemosiderin", "Heme"], a: 1 },
            { q: "Which enzyme in RBCs facilitates CO2 transport?", options: ["Carbonic anhydrase", "Catalase", "Peroxidase", "Hexokinase"], a: 0 },
            { q: "The oxygen-hemoglobin dissociation curve is shifted to the right by:", options: ["High pH", "Low Temperature", "High 2,3-DPG", "Fetal Hemoglobin"], a: 2 },
            { q: "Which globin chains make up HbA (Adult)?", options: ["2 Alpha, 2 Gamma", "2 Alpha, 2 Beta", "2 Alpha, 2 Delta", "4 Beta"], a: 1 },
            { q: "Spectrin deficiency leads to:", options: ["Sickle cell anemia", "Hereditary Spherocytosis", "Thalassemia", "Iron deficiency"], a: 1 },
            { q: "The Buffy Coat contains:", options: ["RBCs and Plasma", "Platelets and WBCs", "Serum and Clot", "Albumin"], a: 1 },
            { q: "ESR is increased in:", options: ["Polycythemia", "Sickle cell anemia", "Inflammation/Pregnancy", "Heart failure"], a: 2 },
            { q: "Haptoglobin functions to bind:", options: ["Free Iron", "Free Hemoglobin", "Copper", "Vitamin B12"], a: 1 },
            { q: "Which anemia is microcytic and hypochromic?", options: ["Pernicious anemia", "Iron deficiency anemia", "Aplastic anemia", "Hemolytic anemia"], a: 1 },
            { q: "Megaloblastic anemia is caused by deficiency of:", options: ["Iron", "EPO", "B12 or Folic Acid", "Protein"], a: 2 },
            { q: "The primary site of haemopoiesis in the 2nd trimester is:", options: ["Yolk sac", "Bone marrow", "Liver/Spleen", "Lymph nodes"], a: 2 },
            { q: "Thrombopoietin is produced primarily by the:", options: ["Bone marrow", "Kidney", "Liver", "Spleen"], a: 2 },
            // 16-30: Immunity & Inflammation
            { q: "Opsonization enhances:", options: ["Chemotaxis", "Phagocytosis", "Diapedesis", "Clotting"], a: 1 },
            { q: "Which complement pathway is triggered by Antigen-Antibody complex?", options: ["Alternative", "Classical", "Lectin", "Common"], a: 1 },
            { q: "Major Histocompatibility Complex (MHC) Class I is found on:", options: ["APC only", "All nucleated cells", "RBCs", "Bacteria"], a: 1 },
            { q: "MHC Class II presents antigens to:", options: ["CD8 T-cells", "CD4 Helper T-cells", "B-cells", "NK cells"], a: 1 },
            { q: "IgA is primarily found in:", options: ["Blood", "Secretions (Tears, Saliva, Milk)", "Lymph", "Placenta"], a: 1 },
            { q: "IgE mediates:", options: ["Primary response", "Type I Hypersensitivity (Allergy)", "Mucosal immunity", "Complement activation"], a: 1 },
            { q: "Natural Killer (NK) cells kill via:", options: ["Phagocytosis", "Perforins and Granzymes", "Antibodies", "NETs"], a: 1 },
            { q: "Interferons are antiviral proteins produced by:", options: ["Bacteria", "Virus-infected cells", "RBCs", "Platelets"], a: 1 },
            { q: "Diapedesis occurs primarily in:", options: ["Arteries", "Veins", "Post-capillary venules", "Lymphatics"], a: 2 },
            { q: "Chemotaxis is defined as:", options: ["Engulfment of bacteria", "Movement towards chemical gradient", "Exit from vessel", "Cell death"], a: 1 },
            // 31-40: Coagulation Details
            { q: "Factor VIII deficiency causes:", options: ["Hemophilia B", "Hemophilia A", "Von Willebrand disease", "Christmas disease"], a: 1 },
            { q: "The extrinsic pathway is triggered by:", options: ["Collagen exposure", "Tissue Factor (III)", "Platelet factor 3", "Calcium"], a: 1 },
            { q: "The intrinsic pathway is monitored by:", options: ["PT", "APTT", "Bleeding time", "Platelet count"], a: 1 },
            { q: "Warfarin acts by inhibiting:", options: ["Thrombin", "Vitamin K epoxide reductase", "Platelet aggregation", "Fibrinogen"], a: 1 },
            { q: "Heparin enhances the activity of:", options: ["Protein C", "Antithrombin III", "Plasminogen", "Factor X"], a: 1 },
            { q: "Tissue Plasminogen Activator (tPA) converts:", options: ["Fibrin to FDP", "Plasminogen to Plasmin", "Prothrombin to Thrombin", "Fibrinogen to Fibrin"], a: 1 },
            { q: "Platelets adhere to collagen via:", options: ["Fibrinogen", "Von Willebrand Factor (vWF)", "Factor VIII", "Thrombin"], a: 1 },
            { q: "Aspirin inhibits platelets by blocking:", options: ["Thrombin receptors", "Cyclooxygenase (TXA2 synthesis)", "ADP receptors", "GP IIb/IIIa"], a: 1 },
            { q: "Clot retraction is mediated by platelet:", options: ["Actin and Myosin (Thrombosthenin)", "Tubulin", "Fibrin", "Spectrin"], a: 0 },
            { q: "Protein C and S function as:", options: ["Pro-coagulants", "Natural anticoagulants", "Fibrinolytic agents", "Platelet activators"], a: 1 }
        ],
        advanced: [
            // 1-20: Clinical Hematology
            { q: "Erythroblastosis fetalis occurs when:", options: ["Mother Rh+, Fetus Rh-", "Mother Rh-, Fetus Rh+", "Mother O, Fetus A", "Mother AB, Fetus O"], a: 1 },
            { q: "RhoGAM (Anti-D) works by:", options: ["Stimulating fetal RBCs", "Destroying fetal RBCs in maternal circulation before sensitization", "Boosting maternal immunity", "Blocking placenta"], a: 1 },
            { q: "Kernicterus involves deposition of bilirubin in the:", options: ["Liver", "Basal Ganglia", "Kidney", "Skin"], a: 1 },
            { q: "In DIC (Disseminated Intravascular Coagulation), there is:", options: ["Only clotting", "Only bleeding", "Widespread clotting followed by bleeding", "High platelet count"], a: 2 },
            { q: "Von Willebrand Disease affects:", options: ["Primary hemostasis (Platelet adhesion) & Factor VIII stability", "Secondary hemostasis only", "Fibrinolysis", "RBC shape"], a: 0 },
            { q: "A 'Shift to the Left' in WBC count implies:", options: ["Viral infection", "Increase in immature neutrophils (Bands)", "Leukopenia", "Lymphocytosis"], a: 1 },
            { q: "The Philadelphia Chromosome is associated with:", options: ["CLL", "CML (Chronic Myeloid Leukemia)", "AML", "ALL"], a: 1 },
            { q: "HbS (Sickle Hemoglobin) involves a mutation replacing:", options: ["Glutamic acid with Valine", "Valine with Glutamine", "Lysine with Valine", "Proline with Histidine"], a: 0 },
            { q: "Thalassemia Major is characterized by:", options: ["Defective Heme synthesis", "Defective/Absent Globin chain synthesis", "Iron deficiency", "B12 deficiency"], a: 1 },
            { q: "Polycythemia Vera is caused by a mutation in:", options: ["JAK2 kinase", "EPO receptor", "GATA-1", "Spectrin"], a: 0 },
            { q: "Which test evaluates the Extrinsic pathway?", options: ["APTT", "PT (Prothrombin Time)", "Thrombin Time", "Bleeding Time"], a: 1 },
            { q: "Idiopathic Thrombocytopenic Purpura (ITP) involves:", options: ["Bone marrow failure", "Autoantibodies against platelets", "Splenic sequestration", "Vitamin K deficiency"], a: 1 },
            { q: "Bernard-Soulier syndrome is a defect in:", options: ["GpIb receptor (Adhesion)", "GpIIb/IIIa receptor", "vWF", "Fibrinogen"], a: 0 },
            { q: "Glanzmann's Thrombasthenia is a defect in:", options: ["GpIb", "GpIIb/IIIa (Aggregation)", "Factor VIII", "TXA2"], a: 1 },
            { q: "Which cytokine stimulates eosinophil production?", options: ["IL-2", "IL-5", "IL-8", "TNF-alpha"], a: 1 },
            { q: "Paroxysmal Nocturnal Hemoglobinuria (PNH) is due to lack of:", options: ["Spectrin", "GPI-anchored proteins (CD55/CD59)", "Hemoglobin", "G6PD"], a: 1 },
            { q: "G6PD deficiency causes hemolysis under:", options: ["Hypoxia", "Oxidative stress", "Acidosis", "Alkalosis"], a: 1 },
            { q: "Bombay Blood phenotype lacks:", options: ["A antigen", "B antigen", "H antigen", "Rh antigen"], a: 2 },
            { q: "Cryoprecipitate is rich in:", options: ["Albumin", "Factor VIII, Fibrinogen, vWF", "Platelets", "WBCs"], a: 1 },
            { q: "Graft-versus-host disease (GVHD) is caused by:", options: ["Recipient T-cells attacking graft", "Donor T-cells attacking recipient tissues", "Antibodies", "Macrophages"], a: 1 },
            // 21-50: Molecular Mechanisms & Physics
            { q: "The Bohr effect describes:", options: ["CO2 binding to Hb", "Effect of pH/CO2 on O2 affinity", "Cl- shift", "Buffering"], a: 1 },
            { q: "The Haldane effect describes:", options: ["O2 affecting CO2 transport", "CO2 affecting O2 transport", "Temperature effect", "2,3-DPG effect"], a: 0 },
            { q: "2,3-DPG binds to:", options: ["Alpha chains", "Beta chains (stabilizing Deoxy-Hb)", "Heme iron", "CO2"], a: 1 },
            { q: "Methemoglobinemia involves iron in the:", options: ["Ferrous state (Fe2+)", "Ferric state (Fe3+)", "Elemental state", "Bound state"], a: 1 },
            { q: "Nitric Oxide (NO) transported by Hb causes:", options: ["Vasoconstriction", "Vasodilation", "Clotting", "Hemolysis"], a: 1 },
            { q: "Hemin inhibits:", options: ["ALA synthase (Heme synthesis)", "Ferrochelatase", "Globin synthesis", "Iron absorption"], a: 0 },
            { q: "Transferrin receptor expression is upregulated by:", options: ["High iron", "Low intracellular iron (IRE-BP system)", "Ferritin", "Hepcidin"], a: 1 },
            { q: "Hepcidin regulates iron by:", options: ["Increasing absorption", "Degrading Ferroportin (blocking release)", "Binding Transferrin", "Increasing Ferritin"], a: 1 },
            { q: "The respiratory burst enzyme is:", options: ["NADPH Oxidase", "Catalase", "SOD", "Myeloperoxidase"], a: 0 },
            { q: "Chronic Granulomatous Disease is a defect in:", options: ["Chemotaxis", "NADPH Oxidase", "Phagolysosome fusion", "Antibody production"], a: 1 },
            { q: "Chediak-Higashi syndrome involves:", options: ["Defective microtubule polymerization", "Lack of integrins", "Lack of selectins", "NADPH oxidase"], a: 0 },
            { q: "Leukocyte Adhesion Deficiency (LAD) type 1 is a defect in:", options: ["Selectins", "Integrins (CD18)", "ICAM-1", "Chemokines"], a: 1 },
            { q: "Multiple Myeloma is a malignancy of:", options: ["T-cells", "Plasma cells", "Myeloblasts", "Monocytes"], a: 1 },
            { q: "Bence-Jones proteins in urine are:", options: ["Albumin", "Free Immunoglobulin Light Chains", "Heavy chains", "Hemoglobin"], a: 1 },
            { q: "Rouleaux formation is caused by:", options: ["High negative charge on RBCs", "Neutralization of Zeta potential by plasma proteins", "Low fibrinogen", "Anemia"], a: 1 },
            { q: "The chloride shift involves exchange of:", options: ["Cl- and Na+", "Cl- and HCO3-", "Cl- and K+", "Cl- and O2"], a: 1 },
            { q: "Relative Polycythemia is due to:", options: ["High EPO", "Bone marrow tumor", "Decreased plasma volume (Dehydration)", "High altitude"], a: 2 },
            { q: "Lead poisoning causes anemia by inhibiting:", options: ["ALA dehydratase & Ferrochelatase", "Globin synthesis", "Iron absorption", "B12 absorption"], a: 0 },
            { q: "Fetal Hemoglobin (HbF) has higher affinity for O2 because:", options: ["It binds 2,3-DPG poorly", "It has 4 alpha chains", "It binds CO2 better", "It is larger"], a: 0 },
            { q: "Which coagulation factor is a Transglutaminase?", options: ["Factor X", "Factor XIII", "Factor II", "Factor V"], a: 1 },
            { q: "Streptokinase acts by:", options: ["Directly degrading fibrin", "Activating Plasminogen (non-specific)", "Blocking Thrombin", "Inhibiting platelets"], a: 1 },
            { q: "Direct Coombs test detects:", options: ["Free antibodies in serum", "Antibodies attached to RBCs", "Blood type", "Viral antigens"], a: 1 },
            { q: "Indirect Coombs test detects:", options: ["Free antibodies in serum", "Antibodies on RBCs", "RBC fragility", "Clotting time"], a: 0 },
            { q: "Massive transfusion can cause:", options: ["Hypercalcemia", "Hypocalcemia (Citrate toxicity)", "Hyperthermia", "Thrombocytosis"], a: 1 },
            { q: "TRALI (Transfusion Related Acute Lung Injury) is caused by:", options: ["Volume overload", "Donor antibodies vs Recipient WBCs", "Bacterial infection", "Allergy"], a: 1 },
            { q: "TACO (Transfusion Associated Circulatory Overload) causes:", options: ["Hypotension", "Hypertension & Pulmonary Edema", "Fever", "Rash"], a: 1 },
            { q: "D-Dimer test is specific for:", options: ["Fibrinogen breakdown", "Cross-linked Fibrin breakdown", "Prothrombin", "Platelet function"], a: 1 },
            { q: "Virchow's Triad includes:", options: ["Stasis, Hypercoagulability, Endothelial injury", "Anemia, Infection, Bleeding", "Pain, Pallor, Pulselessness", "Redness, Heat, Swelling"], a: 0 },
            { q: "Which factor acts as a cofactor for Factor IXa?", options: ["Factor V", "Factor VIII", "Factor X", "Factor VII"], a: 1 },
            { q: "Weibel-Palade bodies in endothelial cells store:", options: ["vWF and P-selectin", "Fibrinogen", "Factor VIII", "Tissue Factor"], a: 0 }
        ]
    },

    "PHS 212": {
        beginner: [
            // 1-10: Neuron Basics
            { q: "The structural unit of the nervous system is the:", options: ["Nephron", "Neuron", "Sarcomere", "Osteon"], a: 1 },
            { q: "Which part of the neuron receives signals?", options: ["Axon", "Dendrite", "Soma", "Terminal"], a: 1 },
            { q: "The gap between two neurons is called the:", options: ["Gap junction", "Synapse", "Node", "Bridge"], a: 1 },
            { q: "The resting membrane potential of a neuron is approx:", options: ["+30 mV", "-70 mV", "0 mV", "-90 mV"], a: 1 },
            { q: "Myelin is produced in the PNS by:", options: ["Astrocytes", "Schwann cells", "Oligodendrocytes", "Microglia"], a: 1 },
            { q: "Myelin is produced in the CNS by:", options: ["Astrocytes", "Schwann cells", "Oligodendrocytes", "Ependymal cells"], a: 2 },
            { q: "Action potentials are generated at the:", options: ["Dendrite", "Axon Hillock", "Soma", "Terminal"], a: 1 },
            { q: "Which ion is most abundant outside the cell?", options: ["Potassium", "Sodium", "Magnesium", "Phosphate"], a: 1 },
            { q: "Which ion is most abundant inside the cell?", options: ["Sodium", "Calcium", "Potassium", "Chloride"], a: 2 },
            { q: "The 'All-or-None' principle applies to:", options: ["Graded potentials", "Action potentials", "Resting potentials", "Synaptic delay"], a: 1 },
            // 11-20: Muscle Basics
            { q: "The functional unit of skeletal muscle is the:", options: ["Myofibril", "Sarcomere", "Fascicle", "Fiber"], a: 1 },
            { q: "Thick filaments are composed of:", options: ["Actin", "Myosin", "Troponin", "Tropomyosin"], a: 1 },
            { q: "Thin filaments are composed mainly of:", options: ["Myosin", "Actin", "Titin", "Myoglobin"], a: 1 },
            { q: "Which muscle type is voluntary?", options: ["Cardiac", "Smooth", "Skeletal", "Visceral"], a: 2 },
            { q: "Which muscle type has intercalated discs?", options: ["Skeletal", "Smooth", "Cardiac", "Multi-unit"], a: 2 },
            { q: "Neurotransmitter at the neuromuscular junction is:", options: ["Adrenaline", "Acetylcholine", "Dopamine", "GABA"], a: 1 },
            { q: "Calcium is stored in the muscle in the:", options: ["Mitochondria", "Sarcoplasmic Reticulum", "T-tubules", "Nucleus"], a: 1 },
            { q: "Muscle contraction requires energy in the form of:", options: ["ADP", "ATP", "GTP", "cAMP"], a: 1 },
            { q: "A motor unit is:", options: ["One neuron & all fibers it supplies", "One fiber & one neuron", "Entire muscle", "Sensory & Motor neuron"], a: 0 },
            { q: "Rigor mortis occurs due to lack of:", options: ["Calcium", "ATP", "Sodium", "Oxygen"], a: 1 },
            // 21-30: General
            { q: "Depolarization is caused by influx of:", options: ["K+", "Na+", "Cl-", "Proteins"], a: 1 },
            { q: "Repolarization is caused by efflux of:", options: ["Na+", "K+", "Ca2+", "Cl-"], a: 1 },
            { q: "Saltatory conduction occurs in:", options: ["Unmyelinated fibers", "Myelinated fibers", "Muscle fibers", "Glands"], a: 1 },
            { q: "Nodes of Ranvier are:", options: ["Insulated areas", "Gaps in myelin sheath", "Synapses", "Cell bodies"], a: 1 },
            { q: "The space between actin and myosin filaments is:", options: ["Z-line", "H-zone", "M-line", "I-band"], a: 1 }, // H-zone varies, simplifying
            { q: "Which protein covers the active site on actin?", options: ["Troponin", "Tropomyosin", "Myosin", "Titin"], a: 1 },
            { q: "Excitation-Contraction coupling involves:", options: ["Sodium", "Calcium", "Potassium", "Chlorine"], a: 1 },
            { q: "White muscles are specialized for:", options: ["Endurance", "Rapid, powerful contraction", "Posture", "Slow contraction"], a: 1 },
            { q: "Red muscles contain high amounts of:", options: ["Glycogen", "Myoglobin", "Fat", "Water"], a: 1 },
            { q: "Fatigue is caused by accumulation of:", options: ["ATP", "Lactic acid", "Glucose", "Oxygen"], a: 1 }
        ],
        intermediate: [
            // 1-15: Membrane Potentials
            { q: "The Nernst equation calculates:", options: ["Action potential amplitude", "Equilibrium potential for one ion", "Membrane permeability", "Conduction velocity"], a: 1 },
            { q: "The Goldman-Hodgkin-Katz equation considers:", options: ["Only K+", "Only Na+", "Concentrations and Permeabilities of multiple ions", "Capacitance"], a: 2 },
            { q: "Hyperpolarization is due to:", options: ["Na+ influx", "Slow closure of K+ channels", "Ca2+ influx", "Na/K pump stop"], a: 1 },
            { q: "Absolute refractory period is due to:", options: ["K+ channel opening", "Na+ channel inactivation", "Ca2+ entry", "Hyperpolarization"], a: 1 },
            { q: "Relative refractory period requires:", options: ["Normal stimulus", "Subthreshold stimulus", "Suprathreshold stimulus", "No stimulus"], a: 2 },
            { q: "Na+/K+ ATPase pumps:", options: ["3 Na in, 2 K out", "3 Na out, 2 K in", "2 Na out, 3 K in", "Equal"], a: 1 },
            { q: "Local anesthetics block:", options: ["Voltage-gated K+ channels", "Voltage-gated Na+ channels", "Ca2+ channels", "Leak channels"], a: 1 },
            { q: "Tetrodotoxin (TTX) blocks:", options: ["Na+ channels", "K+ channels", "Ca2+ channels", "Cl- channels"], a: 0 },
            { q: "TEA (Tetraethylammonium) blocks:", options: ["Na+ channels", "K+ channels", "Ca2+ channels", "Pumps"], a: 1 },
            { q: "Conductance (g) is the reciprocal of:", options: ["Voltage", "Resistance", "Current", "Capacitance"], a: 1 },
            { q: "Length constant (lambda) depends on:", options: ["Membrane resistance/Axial resistance", "Capacitance", "Voltage", "Time"], a: 0 },
            { q: "Time constant (tau) depends on:", options: ["Resistance x Capacitance", "Voltage/Current", "Length/Time", "Speed"], a: 0 },
            { q: "Electronic (Graded) potentials are:", options: ["Propagated", "Decremental", "All-or-none", "Always excitatory"], a: 1 },
            { q: "Threshold potential is reached at:", options: ["-70mV", "-55mV", "+30mV", "0mV"], a: 1 },
            { q: "Overshoot refers to:", options: ["Potential > 0mV", "Potential < -70mV", "RMP", "Threshold"], a: 0 },
            // 16-30: Synapse & NMJ
            { q: "Exocytosis of vesicles is triggered by influx of:", options: ["Na+", "K+", "Ca2+", "Mg2+"], a: 2 },
            { q: "Synaptotagmin acts as a:", options: ["Calcium sensor", "Vesicle docker", "Fusion protein", "Pump"], a: 0 },
            { q: "SNARE proteins are involved in:", options: ["Endocytosis", "Vesicle fusion/Exocytosis", "Transport", "Synthesis"], a: 1 },
            { q: "EPSP involves opening of:", options: ["K+ channels", "Non-specific cation channels (Na+/K+)", "Cl- channels", "Ca2+ pumps"], a: 1 },
            { q: "IPSP involves opening of:", options: ["Na+ channels", "K+ or Cl- channels", "Ca2+ channels", "Mg2+ channels"], a: 1 },
            { q: "Spatial summation occurs:", options: ["At one synapse over time", "From multiple synapses simultaneously", "In the axon", "In muscle"], a: 1 },
            { q: "Temporal summation occurs:", options: ["From multiple neurons", "High frequency from one neuron", "In dendrites only", "In soma only"], a: 1 },
            { q: "Acetylcholinesterase degrades ACh into:", options: ["Acetate and Choline", "Acetyl and Amine", "Acid and Base", "Glucose"], a: 0 },
            { q: "Curare blocks:", options: ["Muscarinic receptors", "Nicotinic ACh receptors", "Adrenergic receptors", "Dopamine receptors"], a: 1 },
            { q: "Botulinum toxin mechanism:", options: ["Blocks ACh receptors", "Cleaves SNAREs (prevents ACh release)", "Blocks Na+ channels", "Inhibits AChE"], a: 1 },
            { q: "Myasthenia Gravis antibodies attack:", options: ["Presynaptic Ca+ channels", "Postsynaptic Nicotinic receptors", "AChE", "Vesicles"], a: 1 },
            { q: "Lambert-Eaton Syndrome antibodies attack:", options: ["Presynaptic Ca2+ channels", "Postsynaptic receptors", "Na+ channels", "K+ channels"], a: 0 },
            { q: "Miniature End Plate Potentials (MEPPs) represent:", options: ["One AP", "Release of one vesicle (quantum)", "Muscle contraction", "Fatigue"], a: 1 },
            { q: "Gap junctions allow:", options: ["Chemical delay", "Electrical transmission", "Unidirectional flow", "Fatigue"], a: 1 },
            { q: "Synaptic delay is approx:", options: ["0.5 ms", "5 ms", "10 ms", "0.1 sec"], a: 0 },
            // 31-40: Muscle Mechanics
            { q: "Isometric contraction:", options: ["Length changes", "Tension changes, length constant", "Movement occurs", "Load lifted"], a: 1 },
            { q: "Isotonic contraction:", options: ["Length constant", "Length changes, tension constant", "No work done", "Postural"], a: 1 },
            { q: "The 'Latch mechanism' is a feature of:", options: ["Skeletal muscle", "Cardiac muscle", "Smooth muscle", "Nerve"], a: 2 },
            { q: "Calmodulin is the calcium sensor in:", options: ["Skeletal muscle", "Smooth muscle", "Cardiac muscle", "Bone"], a: 1 },
            { q: "Tetanus is caused by:", options: ["Low Ca2+", "High frequency stimulation (Summation)", "Fatigue", "ATP depletion"], a: 1 },
            { q: "Starling's Law of muscle states force depends on:", options: ["Initial length", "ATP", "Calcium", "Temperature"], a: 0 },
            { q: "Single unit smooth muscle contains:", options: ["Gap junctions", "No gap junctions", "Motor end plates", "Sarcomeres"], a: 0 },
            { q: "Multi-unit smooth muscle is found in:", options: ["Gut", "Iris of eye/Ciliary muscle", "Uterus", "Bladder"], a: 1 },
            { q: "Phosphocreatine functions to:", options: ["Store Oxygen", "Replenish ATP rapidly", "Break down glucose", "Store Ca2+"], a: 1 },
            { q: "Oxygen debt is:", options: ["Excess O2 consumed during exercise", "Excess O2 consumed after exercise", "Lack of O2", "CO2 production"], a: 1 }
        ],
        advanced: [
            // 1-15: Clinical & Pathology
            { q: "Malignant Hyperthermia is triggered by:", options: ["Curare", "Halothane/Succinylcholine", "Aspirin", "Botox"], a: 1 },
            { q: "Mechanism of Malignant Hyperthermia:", options: ["Defective Na+ channel", "Defective Ryanodine Receptor (Ca2+ leak)", "AChE inhibition", "K+ blockage"], a: 1 },
            { q: "Hypocalcemia causes tetany because:", options: ["Threshold becomes more negative", "Na+ channels become more excitable (threshold rises towards RMP)", "K+ channels block", "Muscles relax"], a: 1 },
            { q: "Hyperkalemia causes:", options: ["Hyperpolarization", "Depolarization and potential cardiac arrest", "Repolarization speed up", "No change"], a: 1 },
            { q: "Duchenne Muscular Dystrophy is a defect in:", options: ["Actin", "Myosin", "Dystrophin", "Titin"], a: 2 },
            { q: "Organophosphates (Insecticides) kill by:", options: ["Blocking ACh release", "Irreversibly inhibiting Acetylcholinesterase", "Blocking Na+ channels", "Blocking Ca2+"], a: 1 },
            { q: "Treatment for Organophosphate poisoning:", options: ["Physostigmine", "Atropine + Pralidoxime", "Curare", "Edrophonium"], a: 1 },
            { q: "Black Widow Spider Venom causes:", options: ["Explosive release of ACh", "Blockage of ACh", "Blockage of Na+", "Muscle paralysis"], a: 0 },
            { q: "Bungarotoxin binds irreversibly to:", options: ["Muscarinic receptors", "Nicotinic receptors", "Na+ channels", "Ca2+ channels"], a: 1 },
            { q: "Multiple Sclerosis affects:", options: ["Schwann cells", "Oligodendrocytes (CNS Myelin)", "Axons", "Soma"], a: 1 },
            { q: "Guillain-Barre Syndrome affects:", options: ["CNS myelin", "PNS myelin (Schwann cells)", "Astrocytes", "Neurons"], a: 1 },
            { q: "Periodic Paralysis is often due to channelopathies of:", options: ["Na+ or Ca2+", "Na+, K+, or Ca2+", "Cl- only", "Water channels"], a: 1 },
            { q: "Eaton-Lambert syndrome is often associated with:", options: ["Thymoma", "Small cell lung cancer", "Breast cancer", "Lymphoma"], a: 1 },
            { q: "Myotonia Congenita involves a defect in:", options: ["Na+ channels", "Cl- channels", "K+ channels", "Ca2+ channels"], a: 1 },
            { q: "Succinylcholine is a:", options: ["Non-depolarizing blocker", "Depolarizing blocker", "AChE inhibitor", "Agonist"], a: 1 },
            // 16-30: Advanced Mechanics
            { q: "The Fenn Effect states:", options: ["Heat production increases with work done", "Force velocity is linear", "Muscle is elastic", "ATP is constant"], a: 0 },
            { q: "Henneman's Size Principle states recruitment order is:", options: ["Large to small", "Small to large motor units", "Random", "Fast to slow"], a: 1 },
            { q: "Active tension is maximal at:", options: ["Shortest length", "Optimal length (Lo)", "Longest length", "Zero length"], a: 1 },
            { q: "Passive tension is due to:", options: ["Actin-myosin", "Connective tissue/Titin", "ATP", "Ca2+"], a: 1 },
            { q: "Velocity of contraction is maximal when:", options: ["Load is maximal", "Load is zero", "Load is medium", "Length is short"], a: 1 },
            { q: "Eccentric contraction means:", options: ["Muscle shortens", "Muscle lengthens while contracting", "Muscle length constant", "Relaxation"], a: 1 },
            { q: "The role of Titin is:", options: ["Contraction", "Passive elasticity & centering myosin", "Ca binding", "ATP hydrolysis"], a: 1 },
            { q: "Nebulin functions to:", options: ["Regulate actin filament length", "Anchor myosin", "Block binding sites", "Pump Ca"], a: 0 },
            { q: "In Smooth muscle, Latch-bridge mechanism allows:", options: ["Fast movement", "Maintenance of tension with low ATP", "Relaxation", "High frequency"], a: 1 },
            { q: "MLCK (Myosin Light Chain Kinase) is activated by:", options: ["Ca-Calmodulin complex", "cAMP", "PKA", "Na+"], a: 0 },
            { q: "MLCP (Phosphatase) causes:", options: ["Contraction", "Relaxation (Smooth muscle)", "Tetanus", "Fatigue"], a: 1 },
            { q: "Nitric Oxide relaxes smooth muscle via:", options: ["cAMP", "cGMP", "IP3", "DAG"], a: 1 },
            { q: "IP3 mechanism releases Ca2+ from:", options: ["Extracellular space", "SR", "Mitochondria", "Nucleus"], a: 1 },
            { q: "Ryanodine Receptors (RyR) are located on:", options: ["Sarcolemma", "SR membrane", "T-tubule", "Mitochondria"], a: 1 },
            { q: "Dihydropyridine Receptors (DHPR) act as:", options: ["Ca2+ release channels", "Voltage sensors", "Pumps", "Enzymes"], a: 1 },
            // 31-50: Nerve Physics & Math
            { q: "If extracellular K+ increases, RMP becomes:", options: ["More negative (Hyperpolarized)", "Less negative (Depolarized)", "Zero", "Unchanged"], a: 1 },
            { q: "If extracellular Na+ decreases, Action Potential amplitude:", options: ["Increases", "Decreases", "Stays same", "Becomes wider"], a: 1 },
            { q: "Rheobase is:", options: ["Minimum time", "Minimum current to excite at infinite time", "Maximum voltage", "Resistance"], a: 1 },
            { q: "Chronaxie is:", options: ["Minimum time at 2x Rheobase", "Minimum current", "Time constant", "Length constant"], a: 0 },
            { q: "A nerve with small chronaxie is:", options: ["Less excitable", "More excitable", "Slow", "Dead"], a: 1 },
            { q: "Conduction velocity is proportional to:", options: ["Diameter", "Square root of Diameter", "Length", "Resistance"], a: 0 },
            { q: "Saltatory conduction increases velocity by:", options: ["Increasing capacitance", "Decreasing membrane capacitance & increasing resistance", "Decreasing resistance", "Adding channels"], a: 1 },
            { q: "Classification: A-alpha fibers are:", options: ["Pain", "Proprioception/Motor", "Touch", "Autonomic"], a: 1 },
            { q: "C-fibers are:", options: ["Myelinated fast", "Unmyelinated slow (Pain)", "Motor", "Touch"], a: 1 },
            { q: "Susceptibility to hypoxia is highest in:", options: ["A fibers", "B fibers", "C fibers", "All equal"], a: 0 },
            { q: "Local anesthetics affect which fibers first?", options: ["A-alpha", "C-fibers (Small unmyelinated)", "A-beta", "A-gamma"], a: 1 },
            { q: "Orthodromic conduction means:", options: ["Normal direction", "Reverse direction", "Both ways", "No conduction"], a: 0 },
            { q: "Antidromic conduction means:", options: ["Normal", "Reverse (towards soma)", "Fast", "Slow"], a: 1 },
            { q: "Compound Action Potential (CAP) is:", options: ["All-or-none", "Graded (sum of many fibers)", "Single fiber", "Infinite"], a: 1 },
            { q: "In the Hodgkin-Huxley model, 'm' gates are:", options: ["Na+ activation", "Na+ inactivation", "K+ activation", "Cl-"], a: 0 },
            { q: "In Hodgkin-Huxley, 'h' gates are:", options: ["Na+ activation", "Na+ inactivation", "K+ activation", "Leak"], a: 1 },
            { q: "Strychnine blocks:", options: ["GABA", "Glycine", "Glutamate", "ACh"], a: 1 },
            { q: "Tetanus toxin prevents release of:", options: ["ACh", "Glycine/GABA (Inhibitory)", "Glutamate", "Serotonin"], a: 1 },
            { q: "Wallerian degeneration occurs:", options: ["Proximal to injury", "Distal to injury", "In the soma", "In the dendrite"], a: 1 },
            { q: "Chromatolysis is a reaction of the:", options: ["Axon", "Cell body (Soma)", "Myelin", "Muscle"], a: 1 }
        ]
    },

    "PHS 213": {
        beginner: [
            // 1-10: Organelles & Basics
            { q: "The 'Powerhouse' of the cell is the:", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi"], a: 1 },
            { q: "Protein synthesis occurs in the:", options: ["Smooth ER", "Rough ER/Ribosomes", "Lysosome", "Centriole"], a: 1 },
            { q: "The 'Suicide bags' of the cell containing hydrolytic enzymes are:", options: ["Peroxisomes", "Lysosomes", "Vacuoles", "Vesicles"], a: 1 },
            { q: "The genetic material (DNA) is primarily housed in the:", options: ["Nucleus", "Cytoplasm", "Ribosome", "Golgi"], a: 0 },
            { q: "The cell membrane is primarily a bilayer of:", options: ["Proteins", "Phospholipids", "Carbohydrates", "Nucleic acids"], a: 1 },
            { q: "Which organelle packages and modifies proteins?", options: ["ER", "Golgi Apparatus", "Mitochondria", "Nucleolus"], a: 1 },
            { q: "Movement of water across a semipermeable membrane is:", options: ["Diffusion", "Osmosis", "Active Transport", "Filtration"], a: 1 },
            { q: "Simple diffusion requires:", options: ["ATP", "Carrier proteins", "Concentration gradient", "Water"], a: 2 },
            { q: "Cell drinking is called:", options: ["Phagocytosis", "Pinocytosis", "Exocytosis", "Lysis"], a: 1 },
            { q: "The liquid component of the cytoplasm is the:", options: ["Cytosol", "Matrix", "Stroma", "Plasma"], a: 0 },
            // 11-20: Transport Basics
            { q: "Active transport requires:", options: ["No energy", "ATP (Energy)", "Osmosis", "Equilibrium"], a: 1 },
            { q: "Na+/K+ pump moves:", options: ["Sodium in", "Sodium out", "Potassium out", "Calcium in"], a: 1 },
            { q: "Which substance can easily diffuse through the lipid bilayer?", options: ["Glucose", "Oxygen (O2)", "Na+", "Protein"], a: 1 },
            { q: "Facilitated diffusion uses:", options: ["ATP", "Carrier/Channel proteins", "Vesicles", "Pumps"], a: 1 },
            { q: "A solution that causes a cell to shrink is:", options: ["Isotonic", "Hypotonic", "Hypertonic", "Equitonic"], a: 2 },
            { q: "A solution that causes a cell to swell is:", options: ["Isotonic", "Hypotonic", "Hypertonic", "Equitonic"], a: 1 },
            { q: "0.9% NaCl is considered:", options: ["Isotonic to blood", "Hypertonic", "Hypotonic", "Toxic"], a: 0 },
            { q: "Which ion is most abundant inside the cell?", options: ["Na+", "K+", "Cl-", "Ca2+"], a: 1 },
            { q: "Which ion is most abundant outside the cell?", options: ["K+", "Na+", "Mg2+", "Protein"], a: 1 },
            { q: "Exocytosis is the process of:", options: ["Entry", "Exit/Secretion", "Digestion", "Division"], a: 1 },
            // 21-30: Cytoskeleton & Communication
            { q: "Microtubules are made of:", options: ["Actin", "Tubulin", "Keratin", "Myosin"], a: 1 },
            { q: "Microfilaments are made of:", options: ["Actin", "Tubulin", "Desmin", "Lamin"], a: 0 },
            { q: "Gap junctions allow:", options: ["Chemical isolation", "Electrical/Chemical communication", "Tight sealing", "Adhesion"], a: 1 },
            { q: "Tight junctions form the:", options: ["Blood-Brain Barrier", "Intercalated disc", "Desmosome", "Synapse"], a: 0 },
            { q: "Desmosomes are for:", options: ["Communication", "Spot welding/Adhesion", "Sealing", "Transport"], a: 1 },
            { q: "Cilia are used for:", options: ["Absorption", "Movement/Sweeping", "Secretion", "Digestion"], a: 1 },
            { q: "Microvilli are used for:", options: ["Movement", "Increasing surface area (Absorption)", "Protection", "Division"], a: 1 },
            { q: "The control center of the cell is the:", options: ["Nucleus", "Mitochondria", "Membrane", "ER"], a: 0 },
            { q: "Apoptosis is:", options: ["Accidental cell death", "Programmed cell death", "Cell division", "Cell eating"], a: 1 },
            { q: "Necrosis is:", options: ["Programmed death", "Pathological/Accidental death", "Cell shrinking", "Cell growing"], a: 1 }
        ],
        intermediate: [
            // 1-15: Transport Mechanisms
            { q: "Which GLUT transporter is Insulin-dependent?", options: ["GLUT1", "GLUT2", "GLUT3", "GLUT4"], a: 3 },
            { q: "GLUT2 acts as a glucose sensor in the:", options: ["Brain", "Muscle", "Liver/Pancreas", "Kidney"], a: 2 },
            { q: "SGLT1 transports glucose via:", options: ["Primary active transport", "Secondary active symport", "Facilitated diffusion", "Antiport"], a: 1 },
            { q: "The Na+/K+ ATPase stoichiometry is:", options: ["3Na in, 2K out", "3Na out, 2K in", "2Na out, 3K in", "Equal"], a: 1 },
            { q: "The Na+/Ca2+ exchanger (NCX) is an example of:", options: ["Symport", "Antiport", "Uniport", "Passive diffusion"], a: 1 },
            { q: "Primary active transport derives energy from:", options: ["Ion gradients", "ATP hydrolysis", "Light", "Heat"], a: 1 },
            { q: "Secondary active transport derives energy from:", options: ["ATP directly", "Electrochemical gradient (usually Na+)", "Glucose", "Pressure"], a: 1 },
            { q: "Aquaporins are specific channels for:", options: ["Ions", "Water", "Glucose", "Urea"], a: 1 },
            { q: "Phagocytosis is performed by:", options: ["RBCs", "Macrophages & Neutrophils", "Platelets", "Neurons"], a: 1 },
            { q: "Receptor-Mediated Endocytosis involves:", options: ["Caveolae", "Clathrin-coated pits", "Simple diffusion", "Aquaporins"], a: 1 },
            { q: "Which pump is responsible for stomach acid secretion?", options: ["Na/K ATPase", "H+/K+ ATPase (Proton Pump)", "Ca2+ ATPase", "V-type ATPase"], a: 1 },
            { q: "The SERCA pump moves Calcium into the:", options: ["Mitochondria", "Sarcoplasmic Reticulum", "Extracellular fluid", "Nucleus"], a: 1 },
            { q: "Osmotic pressure is determined by:", options: ["Size of particles", "Number of particles (Osmolarity)", "Charge of particles", "Type of particles"], a: 1 },
            { q: "Hemolysis occurs when an RBC is placed in a:", options: ["Hypertonic solution", "Hypotonic solution", "Isotonic solution", "Oil"], a: 1 },
            { q: "Crenation occurs when an RBC is placed in a:", options: ["Hypertonic solution", "Hypotonic solution", "Isotonic solution", "Water"], a: 0 },
            // 16-30: Signaling & Cytoskeleton
            { q: "G-protein coupled receptors (GPCRs) span the membrane:", options: ["Once", "Twice", "Seven times", "Four times"], a: 2 },
            { q: "Cyclic AMP (cAMP) is a:", options: ["First messenger", "Second messenger", "Enzyme", "Channel"], a: 1 },
            { q: "Adenylyl cyclase converts:", options: ["ATP to cAMP", "GTP to cGMP", "ATP to ADP", "cAMP to AMP"], a: 0 },
            { q: "IP3 causes the release of:", options: ["Na+", "K+", "Ca2+ from ER", "Cl-"], a: 2 },
            { q: "Which cytoskeletal element forms the mitotic spindle?", options: ["Microfilaments", "Intermediate filaments", "Microtubules", "Spectrin"], a: 2 },
            { q: "Actin is the primary component of:", options: ["Microtubules", "Microfilaments", "Nuclear lamina", "Cilia"], a: 1 },
            { q: "Keratin is a type of:", options: ["Microfilament", "Intermediate filament", "Microtubule", "Motor protein"], a: 1 },
            { q: "Kinesin moves cargo towards the:", options: ["Minus end (Nucleus)", "Plus end (Periphery)", "Mitochondria", "Ribosome"], a: 1 },
            { q: "Dynein moves cargo towards the:", options: ["Minus end (Center)", "Plus end (Periphery)", "Membrane", "Extracellular space"], a: 0 },
            { q: "Which junction allows cell-to-cell communication?", options: ["Tight junction", "Gap junction", "Desmosome", "Hemidesmosome"], a: 1 },
            // 31-40: Biophysics Basics
            { q: "Fick's Law describes:", options: ["Osmosis", "Rate of Diffusion", "Active transport", "Electrical potential"], a: 1 },
            { q: "The Nernst Equation calculates:", options: ["Resting potential", "Equilibrium potential for a single ion", "Action potential", "Osmotic pressure"], a: 1 },
            { q: "The Donnan Effect explains the distribution of ions across a membrane impermeable to:", options: ["Na+", "K+", "Proteins (Charged macromolecules)", "Water"], a: 2 },
            { q: "Cell membrane acts electrically as a:", options: ["Resistor only", "Capacitor and Resistor", "Inductor", "Battery only"], a: 1 },
            { q: "Lipid bilayer is primarily a:", options: ["Conductor", "Insulator (Dielectric)", "Generator", "Receptor"], a: 1 }
        ],
        advanced: [
            // 1-15: Advanced Transport & Pathology
            { q: "Cystic Fibrosis is caused by a defect in:", options: ["Na+ channel", "CFTR (Chloride channel)", "K+ channel", "Ca2+ pump"], a: 1 },
            { q: "The CFTR mutation primarily affects:", options: ["F508", "G551D", "R117H", "All of the above"], a: 3 }, // Depends on depth, F508del is most common
            { q: "Digoxin inhibits Na+/K+ ATPase, leading to increased contractility via:", options: ["Direct Ca2+ entry", "Accumulation of intracellular Na+, slowing NCX", "K+ efflux", "Hyperpolarization"], a: 1 },
            { q: "Cholera toxin causes diarrhea by:", options: ["Blocking Na+ absorption", "Permanently activating Adenylyl Cyclase (cAMP increase)", "Inhibiting CFTR", "Killing cells"], a: 1 },
            { q: "GLUT1 deficiency syndrome affects the:", options: ["Liver", "Blood-Brain Barrier", "Muscle", "Kidney"], a: 1 },
            { q: "Familial Hypercholesterolemia is a defect in:", options: ["LDL Receptor (Endocytosis)", "HDL synthesis", "Fatty acid metabolism", "Exocytosis"], a: 0 },
            { q: "SGLT2 inhibitors (Gliflozins) treat diabetes by:", options: ["Increasing insulin", "Blocking glucose reabsorption in kidney PCT", "Blocking gut absorption", "Increasing GLUT4"], a: 1 },
            { q: "Ouabain inhibits:", options: ["Ca2+ pump", "Na+/K+ ATPase", "Proton pump", "SGLT1"], a: 1 },
            { q: "Multidrug Resistance Protein (MDR) is an:", options: ["ABC Transporter", "P-type ATPase", "Ion channel", "Aquaporin"], a: 0 },
            { q: "I-cell disease involves a defect in:", options: ["M6P tagging (Golgi to Lysosome targeting)", "Ribosomes", "Mitochondria", "Exocytosis"], a: 0 },
            { q: "Zellweger syndrome is a defect in:", options: ["Lysosomes", "Peroxisome biogenesis", "Mitochondria", "ER"], a: 1 },
            { q: "Hereditary Spherocytosis is due to a defect in:", options: ["Hemoglobin", "Spectrin/Ankyrin (Cytoskeleton)", "Iron", "Enzymes"], a: 1 },
            { q: "Duchenne Muscular Dystrophy involves:", options: ["Actin", "Myosin", "Dystrophin (Cytoskeletal anchor)", "Tubulin"], a: 2 },
            { q: "Botulinum toxin cleaves:", options: ["SNARE proteins", "Tubulin", "Actin", "Receptors"], a: 0 },
            { q: "Tetanus toxin targets:", options: ["Neuromuscular junction", "Inhibitory interneurons (SNAREs)", "Muscle fibers", "Sensory nerves"], a: 1 },
            // 16-30: Molecular Motors & Dynamics
            { q: "The '9+2' arrangement refers to:", options: ["Centrioles", "Cilia/Flagella axoneme", "Microvilli", "Intermediate filaments"], a: 1 },
            { q: "Kartagener's syndrome (Primary Ciliary Dyskinesia) involves:", options: ["Defective Dynein arms", "Defective Actin", "Defective Kinesin", "No microtubules"], a: 0 },
            { q: "Treadmilling is a property of:", options: ["Intermediate filaments", "Actin filaments and Microtubules", "DNA", "Lipids"], a: 1 },
            { q: "Dynamic instability is specific to:", options: ["Actin", "Microtubules", "Keratin", "Vimentin"], a: 1 },
            { q: "Listeria monocytogenes moves within cells by hijacking:", options: ["Microtubules", "Host Actin polymerization", "Intermediate filaments", "Kinesin"], a: 1 },
            { q: "Taxol functions as a chemotherapy agent by:", options: ["Destabilizing microtubules", "Stabilizing microtubules (preventing depolymerization)", "Breaking DNA", "Inhibiting glycolysis"], a: 1 },
            { q: "Colchicine inhibits:", options: ["Actin polymerization", "Microtubule polymerization", "Protein synthesis", "DNA synthesis"], a: 1 },
            { q: "Which motor protein moves towards the Minus end of Microtubules?", options: ["Kinesin", "Dynein", "Myosin", "Actin"], a: 1 },
            { q: "Myosin V moves organelles along:", options: ["Microtubules", "Actin filaments", "Intermediate filaments", "DNA"], a: 1 },
            { q: "Nuclear Lamins are:", options: ["Microtubules", "Intermediate filaments", "Microfilaments", "Lipids"], a: 1 },
            // 31-50: Biophysics & Methods
            { q: "The Patch-Clamp technique is used to study:", options: ["Protein synthesis", "Single ion channel currents", "DNA sequence", "Cell movement"], a: 1 },
            { q: "FRAP (Fluorescence Recovery After Photobleaching) measures:", options: ["Membrane fluidity/Protein mobility", "Cell death", "Voltage", "Calcium"], a: 0 },
            { q: "FRET (Fluorescence Resonance Energy Transfer) measures:", options: ["Distance/Interaction between molecules", "Fluidity", "Voltage", "Current"], a: 0 },
            { q: "The reflection coefficient (Sigma) of 1 means:", options: ["Solute freely crosses membrane", "Solute is totally impermeable", "Solute is water", "No osmosis"], a: 1 },
            { q: "The Van't Hoff equation calculates:", options: ["Osmotic pressure", "Diffusion rate", "Voltage", "Resistance"], a: 0 },
            { q: "Gibbs-Donnan equilibrium results in:", options: ["Equal ion distribution", "Unequal distribution of diffusible ions due to non-diffusible proteins", "No potential", "Lysis"], a: 1 },
            { q: "The Space Constant (Lambda) determines:", options: ["How far a potential spreads passively", "How fast it spreads", "Action potential height", "Threshold"], a: 0 },
            { q: "Myelination increases the Space Constant by:", options: ["Decreasing membrane resistance", "Increasing membrane resistance", "Increasing capacitance", "Decreasing diameter"], a: 1 },
            { q: "Capacitance of a biological membrane is typically:", options: ["1 F/cm2", "1 uF/cm2", "100 uF/cm2", "0"], a: 1 },
            { q: "Lipid rafts are rich in:", options: ["Phospholipids only", "Cholesterol and Sphingolipids", "Proteins only", "Water"], a: 1 },
            { q: "Caveolae are a type of lipid raft stabilized by:", options: ["Clathrin", "Caveolin", "Actin", "Tubulin"], a: 1 },
            { q: "Using the Goldman equation, if permeability to K+ increases:", options: ["Membrane hyperpolarizes", "Membrane depolarizes", "No change", "AP fires"], a: 0 },
            { q: "If extracellular K+ is increased, the membrane:", options: ["Hyperpolarizes", "Depolarizes", "Stabilizes", "Repolarizes"], a: 1 },
            { q: "Cryofracture (Freeze-fracture) is best for visualizing:", options: ["Organelles", "Membrane interior faces (E and P faces)", "DNA", "Ribosomes"], a: 1 },
            { q: "Flow Cytometry is used to:", options: ["Measure membrane potential", "Analyze physical/chemical characteristics of cells in fluid", "View organelles", "Culture cells"], a: 1 },
            { q: "Atomic Force Microscopy (AFM) provides:", options: ["Chemical analysis", "Topographical surface map at nano-scale", "Internal view", "Color image"], a: 1 },
            { q: "The main determinant of resting membrane potential is:", options: ["Na+ permeability", "K+ permeability (Leak)", "Cl- permeability", "Ca2+ permeability"], a: 1 },
            { q: "During Apoptosis, Phosphatidylserine moves from:", options: ["Outer to Inner leaflet", "Inner to Outer leaflet ('Eat me' signal)", "Nucleus to Cytoplasm", "Mitochondria to ER"], a: 1 },
            { q: "Ischemia causes cell swelling due to:", options: ["Failure of Na+/K+ pump (ATP depletion)", "K+ efflux", "Cl- efflux", "Ca2+ efflux"], a: 0 },
            { q: "Hydropic degeneration (Cloudy swelling) is a sign of:", options: ["Reversible cell injury", "Irreversible necrosis", "Apoptosis", "Cancer"], a: 0 }
        ]
    },

    "PHS 214": {
        beginner: [
            // 1-10: Basic Hematology & Lab Basics
            { q: "In the determination of Packed Cell Volume (PCV), the layer immediately above the packed red cells is known as the:", options: ["Plasma layer", "Serum layer", "Buffy coat", "True plasma"], a: 2 },
            { q: "The specific gravity of Red Blood Cells is approximately:", options: ["1.027", "1.055", "1.095", "1.000"], a: 2 },
            { q: "Which stain is used for Reticulocyte count?", options: ["Leishman's Stain", "Giemsa Stain", "New Methylene Blue", "Hematoxylin"], a: 2 },
            { q: "Leishman's stain contains:", options: ["Eosin and Methylene Blue in Acetone", "Eosin and Methylene Blue in Methanol", "Safranin and Crystal Violet", "Iodine and Alcohol"], a: 1 },
            { q: "Which anticoagulant acts by chelating Calcium ions?", options: ["Heparin", "EDTA", "Warfarin", "Dicoumarol"], a: 1 },
            { q: "In a WBC count, which squares of the Neubauer chamber are used?", options: ["The 4 corner large squares", "The central large square", "The 5 small central squares", "The entire grid"], a: 0 },
            { q: "Basophils are functionally similar to which tissue cell?", options: ["Macrophages", "Mast Cells", "Plasma Cells", "Fibroblasts"], a: 1 },
            { q: "The uppermost layer of a centrifuged hematocrit tube containing plasma is normally:", options: ["Red", "Straw-colored", "Milky white", "Pink"], a: 1 },
            { q: "The dilution factor used in the standard RBC count using a hemocytometer is:", options: ["1:10", "1:20", "1:100", "1:200"], a: 3 },
            { q: "A 'Left Shift' in a Differential Leukocyte Count refers to:", options: ["Increase in Lymphocytes", "Increase in immature Neutrophils (Band cells)", "Decrease in Eosinophils", "Migration to left side"], a: 1 },
            // 11-20: Basic Hemostasis
            { q: "Bleeding Time primarily assesses:", options: ["Intrinsic pathway", "Extrinsic pathway", "Platelet function and vascular integrity", "Fibrinolysis"], a: 2 },
            { q: "Which factor is 'Factor IV' in the clotting cascade?", options: ["Fibrinogen", "Prothrombin", "Calcium ions", "Tissue Thromboplastin"], a: 2 },
            { q: "Heparin acts as an anticoagulant by activating:", options: ["Protein C", "Antithrombin III", "Plasminogen", "Thromboxane A2"], a: 1 },
            { q: "Clotting Time is prolonged in:", options: ["Thrombocytopenia", "Haemophilia A (Factor VIII deficiency)", "Vitamin C deficiency", "Allergic Purpura"], a: 1 },
            { q: "Which substance is used to reverse the action of Heparin?", options: ["Vitamin K", "Protamine Sulfate", "Fresh Frozen Plasma", "Calcium Gluconate"], a: 1 },
            { q: "Sodium Oxalate prevents clotting by:", options: ["Binding Antithrombin", "Precipitating Calcium", "Destroying Fibrinogen", "Inhibiting Liver synthesis"], a: 1 },
            { q: "What is the normal range for Duke’s Bleeding Time?", options: ["1 – 5 Minutes", "2 – 9 Minutes", "5 – 11 Minutes", "10 – 15 Seconds"], a: 0 },
            { q: "Vitamin K is essential for the synthesis of factors:", options: ["I, II, V, VIII", "II, VII, IX, X", "XI, XII, XIII", "V, VIII, X"], a: 1 },
            { q: "Which cell has a kidney-bean shaped nucleus and is the largest leukocyte?", options: ["Lymphocyte", "Monocyte", "Neutrophil", "Basophil"], a: 1 },
            { q: "What is the function of the 'Spreader Slide' in making a blood smear?", options: ["To fix the cells", "To create a monolayer tongue-shaped film", "To crush the cells", "To stain the cells"], a: 1 },
            // 21-25: Basic GI Lab
            { q: "Which indicator changes from Red (pH 3) to Yellow (pH 5)?", options: ["Phenolphthalein", "Methyl Orange", "Universal Indicator", "Litmus"], a: 1 },
            { q: "The pH of normal fasting gastric juice is approximately:", options: ["1.5 – 3.5", "6.0 – 7.0", "4.0 – 5.0", "7.4"], a: 0 },
            { q: "Pepsinogen is activated to Pepsin by:", options: ["Enterokinase", "Hydrochloric Acid (HCl)", "Trypsin", "Bicarbonate"], a: 1 },
            { q: "Which cells secrete Intrinsic Factor?", options: ["Chief Cells", "Parietal Cells", "G Cells", "Mucous Cells"], a: 1 },
            { q: "The enzyme responsible for the H+ gradient in parietal cells is:", options: ["Na+/K+ ATPase", "H+/K+ ATPase (Proton Pump)", "Ca2+ ATPase", "H+/Na+ exchanger"], a: 1 }
        ],
        intermediate: [
            // 1-15: Hemostasis & Hematology Intermediate
            { q: "Calculate the MCV if PCV = 45% and RBC Count = 5 million/mm³.", options: ["90 fL", "80 fL", "9.0 fL", "33 fL"], a: 0 },
            { q: "Which condition leads to a physiological INCREASE in ESR?", options: ["Sickle Cell Anaemia", "Polycythemia", "Pregnancy", "Spherocytosis"], a: 2 },
            { q: "Which technical error in the Westergren ESR method would falsely INCREASE the sedimentation rate?", options: ["Test at 18°C", "Tilting the tube 3 degrees", "Using blood with Polycythemia", "Delaying the test"], a: 1 },
            { q: "A Color Index (CI) of 0.5 indicates:", options: ["Normochromic anemia", "Hyperchromic anemia", "Hypochromic anemia", "Polycythemia"], a: 2 },
            { q: "What is the clinical significance of 'Toxic Granulation' in neutrophils?", options: ["Viral infection", "Severe bacterial infection", "Lead poisoning", "Vitamin B12 deficiency"], a: 1 },
            { q: "Why is the first drop of blood wiped away during skin puncture?", options: ["Remove bacteria", "Avoid dilution with tissue fluid", "Check lancet", "Warm skin"], a: 1 },
            { q: "In the capillary tube method for clotting time, the endpoint is:", options: ["Fibrin thread appearance", "Cessation of flow", "Color change", "Serum formation"], a: 0 },
            { q: "Prothrombin Time (PT) specifically tests the:", options: ["Intrinsic pathway", "Extrinsic pathway", "Common pathway only", "Platelet function"], a: 1 },
            { q: "Thrombocytopenia (low platelets) would result in:", options: ["Prolonged Clotting Time", "Prolonged Bleeding Time", "Both Prolonged", "Both Normal"], a: 1 },
            { q: "Why is Ivy’s method for Bleeding Time superior to Duke’s?", options: ["Less pain", "Standardizes pressure at 40 mmHg", "Uses earlobe", "Measures intrinsic"], a: 1 },
            { q: "Calculate Bleeding Time (Ivy's) if 12 spots were obtained (15 sec intervals).", options: ["2 mins", "3 mins", "4 mins", "6 mins"], a: 1 },
            { q: "Which test is used to monitor Heparin therapy?", options: ["PT", "APTT", "Bleeding Time", "Thrombin Time"], a: 1 },
            { q: "The International Normalized Ratio (INR) standardizes:", options: ["APTT", "Prothrombin Time (PT)", "Bleeding Time", "ESR"], a: 1 },
            { q: "Hemophilia B is a deficiency of:", options: ["Factor VIII", "Factor IX", "Factor XI", "Factor XII"], a: 1 },
            { q: "Purpura is characterized by:", options: ["Factor deficiency", "Bleeding due to platelet/vascular defects", "High Fibrinogen", "Thrombocytosis"], a: 1 },
            // 16-25: GI Physiology Intermediate
            { q: "In titration of gastric acid, the endpoint with Phenolphthalein is:", options: ["Pink", "Colorless", "Red", "Blue"], a: 0 },
            { q: "Calculate Total Acidity: Titer = 10 ml, NaOH = 0.02N, Sample = 5 ml.", options: ["20 mmol/L", "40 mmol/L", "10 mmol/L", "100 mmol/L"], a: 1 },
            { q: "Histamine stimulates gastric acid secretion by binding to:", options: ["H1 receptors", "H2 receptors", "Muscarinic receptors", "CCK receptors"], a: 1 },
            { q: "What is the effect of Vagotomy on gastric secretion?", options: ["Increases acid", "Decreases basal/stimulated acid", "Increases pepsin", "No effect"], a: 1 },
            { q: "In the perfusion experiment, 25% Urethane is used as:", options: ["Acid stimulant", "Anaesthetic agent", "Anticoagulant", "Buffer"], a: 1 },
            { q: "Which substance inhibits gastric acid secretion?", options: ["Gastrin", "Acetylcholine", "Somatostatin", "Histamine"], a: 2 },
            { q: "The 'Basal Acid Output' (BAO) refers to:", options: ["After meal", "Fasting state", "Max after Histamine", "During sleep"], a: 1 },
            { q: "Which nerve stimulates gastric motility and secretion?", options: ["Vagus", "Splanchnic", "Phrenic", "Sciatic"], a: 0 },
            { q: "Lipton tea (Caffeine) increases gastric acid by:", options: ["Blocking H2", "Inhibiting Phosphodiesterase (increasing cAMP)", "Stimulating Vagus", "Mimicking Gastrin"], a: 1 },
            { q: "In gastric perfusion, the cannula for collection is placed at the:", options: ["Esophagus", "Pyloric sphincter", "Duodenum", "Ileum"], a: 1 }
        ],
        advanced: [
            // 1-15: Advanced Lab Hematology
            { q: "In the Fahraeus effect, why is hematocrit in capillaries lower?", options: ["Lysis", "Axial migration (plasma-rich periphery)", "Absorption", "Blockage"], a: 1 },
            { q: "The 'Battlement' method of counting WBCs prevents:", options: ["Recounting", "Distribution bias", "Only granulocytes", "Lysis"], a: 3 }, // Note: Option 4 "Both A and B" in original mapped to D (index 3) here? Original question had A/B/C/D. Let's assume D is correct.
            { q: "Which leukocyte has a bi-lobed nucleus and large brick-red granules?", options: ["Neutrophil", "Eosinophil", "Basophil", "Monocyte"], a: 1 },
            { q: "Achlorhydria is a characteristic feature of:", options: ["Zollinger-Ellison", "Pernicious Anemia", "Duodenal Ulcer", "Gastritis"], a: 1 },
            { q: "Zollinger-Ellison Syndrome is caused by a tumor secreting:", options: ["Histamine", "Gastrin", "Secretin", "Pepsin"], a: 1 },
            { q: "The cephalic phase of gastric secretion is mediated by:", options: ["Gastrin", "Vagus nerve", "Secretin", "CCK"], a: 1 },
            { q: "Omeprazole reduces acid secretion by inhibiting:", options: ["H2 receptors", "H+/K+ ATPase", "Gastrin receptors", "ACh release"], a: 1 },
            { q: "Hyperchlorhydria is associated with:", options: ["Gastric Carcinoma", "Duodenal Ulcers", "Pernicious Anemia", "Hypothyroidism"], a: 1 },
            { q: "In Osmotic Fragility, hemolysis normally begins at NaCl conc. of:", options: ["0.9%", "0.50% – 0.45%", "0.30% – 0.33%", "0.85%"], a: 1 },
            { q: "A 'Shift to the Right' in Osmotic Fragility curve indicates:", options: ["Increased resistance (Thalassemia)", "Increased fragility (Spherocytosis)", "Normal", "Polycythemia"], a: 0 },
            { q: "Hereditary Spherocytosis is characterized by:", options: ["Decreased fragility", "Increased Osmotic Fragility (Shift to Left)", "Sickle cells", "Target cells"], a: 1 },
            { q: "Why does Thalassemia decrease osmotic fragility?", options: ["Spherocytic", "Target cells (excess membrane)", "Rigid membrane", "HbF"], a: 1 },
            { q: "Mean Corpuscular Fragility (MCF) is NaCl conc. causing:", options: ["10% Hemolysis", "50% Hemolysis", "100% Hemolysis", "0%"], a: 1 },
            { q: "Which solution is Isotonic to human RBCs?", options: ["0.45% NaCl", "0.9% NaCl", "5.0% NaCl", "Distilled Water"], a: 1 },
            { q: "Specific Gravity of whole blood is measured using:", options: ["Falling Drop (Copper Sulfate)", "Westergren", "Sahli", "Wintrobe"], a: 0 },
            // 16-25: Immunohematology & Advanced Lab
            { q: "In Copper Sulfate method, if drop sinks rapidly, Hb is:", options: ["Lower", "Higher (>100%)", "Equal", "Zero"], a: 1 },
            { q: "Landsteiner’s Law states:", options: ["Antigen present = Antibody absent", "Type O has A/B antigens", "Rh+ creates antibodies", "Agglutination at 37C"], a: 0 },
            { q: "Universal Recipient is:", options: ["O Rh-", "A Rh+", "AB Rh+", "B Rh-"], a: 2 },
            { q: "Erythroblastosis Fetalis occurs when:", options: ["Mom Rh+, Fetus Rh-", "Mom Rh-, Fetus Rh+", "Both Rh-", "Mom O, Fetus A"], a: 1 },
            { q: "The 'Major Side' cross-match mixes:", options: ["Donor cells + Recipient serum", "Donor serum + Recipient cells", "Donor cells + Donor serum", "Saline + Recipient"], a: 0 },
            { q: "Agglutination is caused by reaction between:", options: ["Fibrinogen/Thrombin", "Agglutinogen/Agglutinin", "Platelets/Collagen", "Hb/O2"], a: 1 },
            { q: "Bombay Phenotype (Oh) is characterized by:", options: ["Lack of H antigen", "Presence of A and B", "Lack of Rh", "Excess H"], a: 0 },
            { q: "Normal Specific Gravity of Plasma is approx:", options: ["1.055", "1.027", "1.090", "1.000"], a: 1 },
            { q: "What is the role of Sphygmomanometer in Ivy’s method?", options: ["Stop flow", "Maintain 40 mmHg venous occlusion", "Measure BP", "Ischemia"], a: 1 },
            { q: "Role of the Vagus nerve in gastric secretion:", options: ["Inhibits", "Stimulates acid/pepsin/motility", "No effect", "Stimulates somatostatin"], a: 1 }
        ]
    }
};
